### ISSUE TITLE
We need to get a CLA - Contributor License Agreement up and running - everyone need to sign this

### ISSUE THREAD

**Issue by einari** [IFRCGo/cbs#1]
Look at using something like [CLA Assistant](https://cla-assistant.io) or  [CLAHub](https://www.clahub.com/pages/why_cla)

**Comment by karolikl** [comment]
Proposed CLA shared with core team on slack. Will use CLA assistant when proposed CLA has been accepted.

**Comment by karolikl** [comment]
Closing as the Red Cross doesn't want one.
