### ISSUE TITLE
Create a build template for .NET projects

### ISSUE THREAD

**Issue by einari** [IFRCGo/cbs#10]
**Consider the following**:

- FAKE
- CAKE

Suggest running builds on AppVeyor and possibly also a Travis version - to make sure it compiles correct on Linux as well. 

Some of the .NET Tools we would like to use don't necessarily run on Linux on .NET Core or even Mono. Meaning that we should use AppVeyor as the primary build for .NET. 
For instance, if we would get sponsorship and chose to use something like [NDepend](https://www.ndepend.com) for monitoring code quality, this only runs on Windows for now.

Depending on the versioning regime, we want to deploy Container images to the Red Cross registry.

Context based build. Everything in **Source** folder should then have a SLN file associated and also a Docker file associated.

```
+-- Source
|   +-- <Bounded Context>
|   |    <Bounded Context>.sln
|   |    Dockerfile
```

Suggest we have a build per bounded context and use the [filtering in AppVeyor](https://www.appveyor.com/docs/how-to/filtering-commits/) to accomplish this.

It is fully possible to generate Docker images and publish in AppVeyor as well. Read more [here](https://stefanscherer.github.io/setup-windows-docker-ci-appveyor/)

We might not need something like Travis at all, since Docker could also then be our build for Linux. The best possible way to use Docker for this purpose is to use its support for multiple FROM statements - one where you do the build and one where you package what should be part of the image. Read more about it [here](https://docs.docker.com/engine/reference/builder/#environment-replacement).

An example of a Dockerfile that does this:

```
# Build the .NET part
FROM microsoft/dotnet:2.0.0-sdk AS dotnet-build
WORKDIR /src
COPY ./NuGet.Config ./
COPY ./Source/Common/. ./Common/
WORKDIR /src/YourProject/Web
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build the static content part
FROM node:latest AS node-build
WORKDIR /src
ADD package.json ./
COPY ./Source/. ./Source/
COPY ./Modules/JavaScript.Build/. ./Modules/JavaScript.Build/
RUN ["npm","install","-g", "gulp"]
RUN ["npm","install"]
WORKDIR /src/Source/YourProject/Web
RUN ["gulp", "html", "javascript", "less", "content"]

# Build runtime image
FROM microsoft/dotnet:2.0.0-runtime
WORKDIR /app
COPY --from=dotnet-build /src/YourProject/Web/out ./
COPY --from=node-build /src/Source/YourProject/Web/wwwroot ./wwwroot
EXPOSE 5000
ENTRYPOINT ["dotnet", "Web.dll"]
```

**Comment by karolikl** [comment]
I've set up a CakeBuild in AppVeyor, but I need to connect the repo to IFRCs AppVeyor account (when it's created) and document how the builds should be configured per project. 

Last but not least, we need to create a docker image as part of the build.

**Comment by sheeeng** [comment]
Initial basic and rough implementation is submitted on #190.

**Comment by karolikl** [comment]
We still have multiple appveyor.yml files in the repo, there should only be one (in the Build folder) and all the projects should use this.

**Comment by anderaus** [comment]
@karolikl yeah, I was a bit confused by this - but didn't have access to the AppVeyor account so I couldn't look into the details. I assume there are several builds set up in AppVeyor pointing to separate appveyor files now? And the intention is to use different env settings instead?

**Comment by karolikl** [comment]
Exactly 👍 I think the Example project and the VolunteerReporting project might use the correct file, but Admin I'm not entirely sure about.

**Comment by karolikl** [comment]
Update: Each project will need it's own appveyor.yml file. It's better to have all configuration in source control than in a AppVeyor UI. It makes it a lot easier for people to set up builds towards their own forks.
