### ISSUE TITLE
Bug in time range when retrieving the Analytics overview page

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#1069]
When retrieving the charts on the Analytics overview page, you pass in startDate and endDate to the API. For the table you pass in the number of weeks to retrieve data from. 

When passing in startDate and endDate, where endDate == today, the API will default to todays date at 00:00, meaning reports that have come in today will not be displayed.

When passing in the number of weeks, the endDate defaults to DateTimeOffset.Now.Date, which is also 00:00. 

For all the 3 APIs used on the Analytics overview page, we need to ensure the timestamp defaults to the current timestamp of the call.

**Comment by esp0** [comment]
If "endDate = tomorrow", the API will also default to "tomorrow at 00:00". If the user can only select a date for the "endDate", maybe use something like this?
`filterEndDate = userInputEndDate.Date.AddDays(1).AddTicks(-1);`

**Comment by agnetedjupvik** [comment]
There is no requirement to fetch in a user-given interval right now, so I'm closing this.
