### ISSUE TITLE
Analytics does not run locally after adding application insights logging

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#1070]
After PR #1064, the Analytics bounded context does not run locally. The error I get is this: 
![image](https://user-images.githubusercontent.com/5235776/56488339-674b0d80-64de-11e9-884d-32f1e9a7ef38.png)

If i comment out the following (in Program.cs) it works: 
`     //.ConfigureLogging(builder => {
                //    builder.AddApplicationInsights(Environment.GetEnvironmentVariable("ASPNETCORE_APPINSIGHTS_INSTRUMENTATIONKEY"));
                //    builder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>
                //                    ("Analytics.Program", LogLevel.Trace);
                //    builder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>
                //                    ("Analytics.Startup", LogLevel.Trace);
                //})`

Are we missing ASPNETCORE_APPINSIGHTS_INSTRUMENTATIONKEY?

**Comment by gardnk** [comment]
The ASPNETCORE_APPINSIGHTS_INSTRUMENTATIONKEY is an environment variable so it needs to be available locally. I'm running from Visual Studio Code and have it configured in the launch.json like this

```
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/Source/NotificationGateway/Core/bin/Debug/netcoreapp2.1/Core.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Source/NotificationGateway/Core",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_APPINSIGHTS_INSTRUMENTATIONKEY": "36bdf7e0-884f-4391-8f08-11ebd48b9023"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        }
```

**Comment by gardnk** [comment]
Now it works when running locally using docker-compose also. All that is needed is having ASPNETCORE_APPINSIGHTS_INSTRUMENTATIONKEY configured on your host machine.

**Comment by gardnk** [comment]
@karolikl Now it should run locally also without ASPNETCORE_APPINSIGHTS_INSTRUMENTATIONKEY

**Comment by gardnk** [comment]
#1074 closes this

**Comment by alexanderhoset** [comment]
@gardnk if you build it without compose it stil fails .. dotnet run in web folder.

**Comment by gardnk** [comment]
@alexanderhoset Does it fail because of application insights key missing? Which bounded context? I'm looking at another build error now also so might be related to that.
