### ISSUE TITLE
Add more total-columns in excel export

### ISSUE THREAD

**Issue by esp0** [IFRCGo/cbs#1084]
The following new columns are needed in the Excel export:

* Total people
* Total over 5
* Total under 5
* Total females
* Total males

**Comment by raubreywhite** [comment]
One problem! You cant have:

Total over 5
AND
Total under 5

Because then 5 year olds dont belong to any group.

I think it needs to be

Total 0 to 4
Total 5 and over

**Comment by esp0** [comment]
That is actually what i did when implementing this, just forgot to update the issue. Thanks anyway for noticing!
