### ISSUE TITLE
Replace GridListTile with Grid

### ISSUE THREAD

**Issue by gardnk** [IFRCGo/cbs#1086]
The [national society overview component](https://github.com/IFRCGo/cbs/blob/master/Source/Analytics/Web.Frontend/src/components/NationalSocietyOverview.js) in the analytics project uses GridListTile components where Grid is semantically correct to use.

As per the design in [UXPin](https://preview.uxpin.com/6f7c2440d8ba5f7888d63932bbc82c4138712847#/pages/109448044/simulate/no-panels) two grids are needed, splitting the screen in half. 

See [Material-UI Grid Docs](https://material-ui.com/layout/grid/)

**Comment by alexanderhoset** [comment]
This will now be a part of a bigger PR from @agnetedjupvik
