### ISSUE TITLE
dotnet build changes read models and commands

### ISSUE THREAD

**Issue by gardnk** [IFRCGo/cbs#1094]
The docker-compose stopped working for me locally, so I tried to build only reporting and it made some changes in the read models and commands for the Web project.

Is this related to the upgrade to Dolittle v3? @woksin 

![image](https://user-images.githubusercontent.com/14860062/58232513-fb0c3580-7d39-11e9-841a-6dc1300a12c7.png)

**Comment by woksin** [comment]
Yeah, the one on the right should be correct. The build tool now makes enums be represented as numbers in the proxies

**Comment by woksin** [comment]
Is that causing problems?

**Comment by gardnk** [comment]
It's causing Reporting frontend to crash because the commands and enums in javascript are not updated.

**Comment by gardnk** [comment]
The docker-compose issue was an issue with docker on my machine, not related to this.

#1095 Fixes build error for reporting frontend
