### ISSUE TITLE
[DataCollector creation] Automatically fill Region, District and Village based on coordinates

### ISSUE THREAD

**Issue by cathinkaw** [IFRCGo/cbs#1100]
When creating a data collector, if I choose coordinates in the map, or writes coordinates manually, then the region, district and village should be selected automatically.

![image](https://user-images.githubusercontent.com/1155078/58413323-c8837500-8078-11e9-9b91-1d1d6f419aa1.png)

**Comment by monsij** [comment]
Up for it! @cathinkaw

**Comment by esp0** [comment]
> Up for it! 

Any progress on this @monsij ? Should I assign this issue to you?

**Comment by esp0** [comment]
@gardnk I dont see how your commit solves this issue? 

> region, district and village should be selected automatically

**Comment by gardnk** [comment]
@esp0 You're right, my commit is only validation and doesn't solve this. But it is part of #1208 which solves it

**Comment by esp0** [comment]
Perfect!
