### ISSUE TITLE
[Country overview] Remove graphs that should no longer be on the overview page

### ISSUE THREAD

**Issue by cathinkaw** [IFRCGo/cbs#1101]
Remove the following graphs:
- Case reports per gender
- Case reports per age group
- Case reports per health risk

These graphs should be used on other pages, so the code itself doesn't need to be deleted.

**Comment by cathinkaw** [comment]
Country overview per 28.05.19 sketches for reference:
![image](https://user-images.githubusercontent.com/1155078/58710933-ba598f80-83bd-11e9-9ff5-aa43342f8888.png)

**Comment by agnetedjupvik** [comment]
The graphs are gone now. However, the landing page isn't 100% similar to this sketch, but I think a landing page refactor can be another issue?

**Comment by cathinkaw** [comment]
I agree @agnetedjupvik.
