### ISSUE TITLE
change title in platform columns

### ISSUE THREAD

**Issue by tineml** [IFRCGo/cbs#1109]
The title for age groups are changed for the excel export, but still says > and < in the platform linelist itself. This should als be changed to males under 5, males 5 and older, females under 5, females five and older.

**Comment by tineml** [comment]
![image](https://user-images.githubusercontent.com/22004770/58766339-b1172100-857d-11e9-9fe5-4575c8722eaf.png)

**Comment by esp0** [comment]
Will the platform still look nice on small screens if we expand these 4 columns by including all this text?
