### ISSUE TITLE
[Country overview] Table showing #cases/healt risk/region for last 7 days

### ISSUE THREAD

**Issue by cathinkaw** [IFRCGo/cbs#1115]
For a country there should be a table showing data for the last 7 days:
- all health risks and the amount of cases of each healt rikst per region.
- Each cell having a case should be highlighted so its easier to detect where there have been cases the last 7 days

![image](https://user-images.githubusercontent.com/1155078/58713032-0eff0980-83c2-11e9-8fd5-ff0d66e701c9.png)

https://github.com/IFRCGo/cbs/wiki/Analytics

**Comment by agnetedjupvik** [comment]
WIP Branch: [Here](https://github.com/agnetedjupvik/cbs/tree/table)

<img width="629" alt="Screen Shot 2019-06-05 at 10 31 51 AM" src="https://user-images.githubusercontent.com/10497878/58941971-26047980-877d-11e9-90d1-2e8efd8a8ac0.png">

Chose to fade numbers when a district has 0 cases of a healthRisk, but we can alter this if something else is nicer for the user.

**Comment by agnetedjupvik** [comment]
The data is currently structured like this: 

`
healthRiskName: "Measels",  
regions: [  
  {name: "Dakar",  
   numberOfCaseReports: 15. 
  },  
  ...  
]  
`

This is why the axes are flipped as opposed to the sketch. I can get it to flip if we think it is nice for the user.

**Comment by tineml** [comment]
There will probably be more locations than helath risk, so could be more user friendly to flip it to Cathinka's drawing.

**Comment by agnetedjupvik** [comment]
Good point, I'll take a look at that @tineml :)

**Comment by agnetedjupvik** [comment]
Here's the most recent version. PR is updated.
![Screen Shot 2019-06-06 at 3 51 37 PM](https://user-images.githubusercontent.com/10497878/59038248-018ac900-8873-11e9-9898-e16474112d08.png)
