### ISSUE TITLE
Set up a block in the platform to not accept commercial messages. These are often short numbers or text. 

### ISSUE THREAD

**Issue by tineml** [IFRCGo/cbs#1133]
We need a block that only exclude comercials. We do not want to block wrong format and unknown regular phone numbers. 

Example of commercial message: 
![image](https://user-images.githubusercontent.com/22004770/60167008-7e6dea80-9802-11e9-8b4e-b4989bb63407.png)

**Comment by esp0** [comment]
After discussing this with @tineml these rules should be used to identify commercial messages:
- The origin/sender number is shorter than 5 letters
- The origin/sender number contains letters

The recommended way to remove the commercial messages is to change the query that returns `CaseReportsForListing` to filter them out. This makes it easy to change the filter at a later stage if it includes too many or too few reports.
