### ISSUE TITLE
AlertSMSNotificationSentToHealthWorker

### ISSUE THREAD

**Issue by torstesu** [IFRCGo/cbs#129]
**Description**
When an alert is raised or escalated, a SMS containing information related to the event is sent. The SMS will also include a link to a form related to the alert for the health worker to fill out.

**Class**
ClassName, PropertyNames, Type etc.

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
