### ISSUE TITLE
AlertFieldReportNarrativeCreated

### ISSUE THREAD

**Issue by torstesu** [IFRCGo/cbs#130]
**Description**
When a health worker has conducted the necessary investigation, the form previously sent out is filled out and submittet. This event contains the narrative of the report.

**Class**
ClassName, PropertyNames, Type etc.

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
