### ISSUE TITLE
AlertSMSMessageSentToVolunteer

### ISSUE THREAD

**Issue by torstesu** [IFRCGo/cbs#131]
**Description**
When an alert is raised, a predefined SMS message is sent to the volunteer. The SMS message is localized to the language of the volunteer.

**Class**
ClassName, PropertyNames, Type etc.

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
