### ISSUE TITLE
AlertCustomSMSMessageSentToVolunteer

### ISSUE THREAD

**Issue by torstesu** [IFRCGo/cbs#132]
**Description**
When a health worker has conducted the necessary investigation, the form previously sent out is filled out. The form contains a field for the health worker to send a custome SMS message to the relevant volunteers. This event is published when the SMS is sent.

**Class**
ClassName, PropertyNames, Type etc.

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
