### ISSUE TITLE
CaseReportReceived

### ISSUE THREAD

**Issue by Molokai** [IFRCGo/cbs#133]
```
        public Guid CaseReportId { get; set; }
        public Guid DataCollectorId { get; set; }
        public Guid HealthRiskId { get; set; }
        public string Origin { get; set; }
        public int NumberOfMalesUnder5 { get; set; }
        public int NumberOfMalesAged5AndOlder { get; set; }
        public int NumberOfFemalesUnder5 { get; set; }
        public int NumberOfFemalesAged5AndOlder { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public DateTimeOffset Timestamp {get; set;}
```

Existing entry:

### Description
Event emitted by VolunteerReporting when a DataCollector (reporter / volunteer) has submitted a case report that has been successfully parsed (for example submitted a correctly formatted SMS).

The event contains the following information:
- ID of the DataCollector
- Timestamp of the submission
- If it is a single case report or an aggregate report (see #44 #45 #46 )
- Aggregated list of elements per unique composition of health risk, gender and age
```
caseList : [
        {"healthRisk" : "51BBA12C-7E52-4DE8-8D0C-114E32CFBD04",
         "gender" : "male",
         "age" :  2,
         "numberOfCases" : 3},

        {"healthRisk" : "51BBA12C-7E52-4DE8-8D0C-114E32CFBD04",
         "gender" : "female",
         "age" : 1,
         "numberOfCases" : 2,}
         ]

TODO: HOW is age represented for the Aggregrate Case Report where the columns are only less than 5 or greater than 5.

FOR EXAMPLE:
caseList : [
        {"healthRisk" : "51BBA12C-7E52-4DE8-8D0C-114E32CFBD04",
         "gender" : "male",
         "ageBracket" :  "Below 5",
         "numberOfCases" : 3},

        {"healthRisk" : "51BBA12C-7E52-4DE8-8D0C-114E32CFBD04",
         "gender" : "female",
         "ageBracket" : "Above 5",
         "numberOfCases" : 2}
         ]


- Supplemental data?  (could include geo tagging if available. TBD)

### Class

**Comment by Velcrow81** [comment]
Should we have a different event for aggregated events? I.e. CaseReportsReceived? That way, they can contain only the information relevant for the type of case?

**Comment by Velcrow81** [comment]
Can one text message contain multiple single case reports? If so, I think the text parsing must be updated. I see that it says numberOfCases in both multiple and single case report.

**Comment by Velcrow81** [comment]
Should it be possible with a third option in gender? I.e. 3 like unkown, does not want to say, transgender, other etc

**Comment by Velcrow81** [comment]
Should we continue to use the codes for gender(sex) i.e. 1 and 2 (and possibly 3) in the event, or should we write it out as a string i.e. "male", "female", "other"

**Comment by Velcrow81** [comment]
Should there be a scenario where we do not know the datacollector and still create a case? Should DataCollectorId be optional or should we create one DataCollector for "unknown"?

**Comment by Velcrow81** [comment]
Could this be the properties for the the single case event?

```
public Guid Id { get; set; }
public Guid HealthRiskId { get; set; }        
public Guid DataCollectorId { get; set; }
public DateTimeOffset Timestamp { get; set; }
public int Age { get; set; }
public string Gender { get; set; }
public string Longitude { get; set; }
public string Latitude { get; set; }
```

**Comment by karolikl** [comment]
Great questions! 

One text message can contain multiple case reports, but only relating to one health event (such as the example in #46). So you cannot have _one_ text message reporting on two different health events, you would then have to send two texts.

I don't think we should have a separate event for aggregated events, as I really don't see the need for one. If you think of a scenario where two separate events can be useful, please share.

Gender: A third option is a good idea. I think we should be the only bounded context that has to know the cryptic IDs in the text message format (apart from the health risk ID, the other bounded contexts will need to know this as well), and therefore I prefer to type it out to make it more obvious. It also means we can change the format of the text messages without having to affect any of the other bounded contexts.

We have to be able to create anonymous case reports (#170), so DataCollectorId should be optional. 

As for the properties, do we need Longitude & Latitude? 
I'm also a bit unsure of the name of this event. As we are the creators of the case report, should it be called "CaseReportCreated" or similar?

**Comment by Velcrow81** [comment]
Great clarification :) One text message on each health event, either in aggragate or singular form. Check :)

We introduce a third option for gender with code 3 which will translate to "Other". And we send "Male", "Femle", and "Other" in the event. Check.

DataCollectorId will be nullable. Check.

I can remove Longitude & Latitude, but this is something that come with the sms, and if we have the location data, it might be used for i.e. visualization on a map in reports. If we keep it, other parts of the system can choose to use it or not, and we don't decide for them.

When it comes to naming, CaseReportCreated certainly works. but I feel CaseReportReceived might capture the domain better. The volunteer write a case report and submits it using sms. After we parse the sms and verify it, we can then confirm that we have recieved a case report. It is the volenteer that create the case report by typing the sms. 

And finally, should we use multiple events? I don't quite understand what the case list in the event should be. When a single case is reported, there is only one patient. This could be captured as: 

```
CaseReportCreated

public Guid Id { get; set; }
public Guid HealthRiskId { get; set; }        
public Guid? DataCollectorId { get; set; }
public DateTimeOffset Timestamp { get; set; }
public int Age { get; set; }
public string Gender { get; set; }
public string Longitude { get; set; }
public string Latitude { get; set; }
```
For the aggregate scenario we could do this:

```
CaseReportsCreated

public Guid Id { get; set; }
public Guid HealthRiskId { get; set; }        
public Guid? DataCollectorId { get; set; }
public DateTimeOffset Timestamp { get; set; }
public int NumberOfMalesUnder5 { get; set; }
public int NumberOfMalesOver5 { get; set; }
public int NumberOfFemalesUnder5 { get; set; }
public int NumberOfFemalesOver5 { get; set; }
public int NumberOfOtherUnder5 { get; set; }
public int NumberOfOtherOver5 { get; set; }
public string Longitude { get; set; }
public string Latitude { get; set; }
```

We could use a complex type for case list, but im not sure if we should use complex types in an event.

The alternative is to send multiple CaseReportCreated based on the aggregate, but that would introduce a lot of cases with the age 4 or 6 (or some other ages under and over 5). Anyone have a suggestion for this?

**Comment by Velcrow81** [comment]
Hm. Im a bit confused about the age. In "Parse an SMS containing a single case report #44" the age is Age of Case in years (12 in the example). In "Converting single case reporting to default aggregate case reporting format #45", age is a code in the 2 hash message (1 is under 5, 2 is over 5). Report database #48 seems to also use age as number in years. Perhaps we should always emit an event where age is listed as either over or below 5 even though we know what it is in single case reports

**Comment by karolikl** [comment]
You've convinced me on the naming, let's stick with CaseReportReceived! You also have a good point about the latitude/longitude, let's keep it there in case Alerts or Reporting wants this information. 

The reason I want to emit the same event for a single report and aggragate reports is to simplify the parsing that the Alert team has to do. Looking at the structure of the aggregate event that you have proposed above, we can use the same event for a single report (the property NumberOf* will always equal 1). This will give us the freedom to change the text message formats in the future without having to rework anything else than our own parsing. Of course, this assumes that we can use over 5 and under 5 for age, regardless of whether the report is single or aggregate, I can check with the RC if this is ok. 

About complex types, I'm not sure either. @einari, any comments on using complex types in events?

**Comment by Velcrow81** [comment]
@karolikl : Can you also check with the Red Cross if we should introduce a third gender? This would require that we update the parsing, but that is easy. We could also make it backwards combatible, so if people send in using the existing aggregate format, nothing changes. If they add another two hashes to the text, that will mean other under 5 and other over 5

**Comment by karolikl** [comment]
From Anine: "Although incorrect we're sticking with binary F/M in volunteer reporting, as adding an 'other' category would add another 2 variables and probably confuse more than do good. We can add 'other sex' category to volunteer registration though."

So in a text message, we will only receive F/M.

**Comment by Velcrow81** [comment]
Ok. We will focus on female and male categories for now :)

**Comment by Velcrow81** [comment]
DataCollectorId will no longer be nullable. See discussion in #170

**Comment by Velcrow81** [comment]
@einari : I see that you have introduced MultipleCaseReportsReceived and MultipleCaseReportsFromUnknownDataCollectorReceived after the refactoring (doLittle). Why have you introduced the multiple case report events? According to discussion with @karolikl on Oct 4 (see above), it was agreed to emit only CaseReportReceived for all scenarios and in the single report case we would set i.e. NumberOfMalesUnder5 = 1. Could you help me understand why this was done? Is it better domain events? :) Aslo, could you update the events overview project when you introduce new events so that other teams can see what we emit :)

**Comment by einari** [comment]
From what I can see, transforming the incoming input to this one generic event you lose information when you have the information - plus you lose possibly important context. 

The single case report holds exact age - while this is lost in the other. So if single cases gets reported and is a required feature, we could start getting more insight into the data. 

When I looked at the original code I saw you went through temporary objects that kept this information and thought it made more sense to formalise these as events. Events should really be as specific as possible and should never be dried up.

**Comment by Velcrow81** [comment]
@karolikl : Was it RC that wanted everything reported as a multiple report? Will this change be OK for other projects (i.e. Alerts). I'm OK with it, and @einaris reasoning makes a lot of sense. And since he rarely makes sense, we should celebrate this joyous occasion :)

**Comment by einari** [comment]
Hehehe..   Good to hear I can make sense every now and then and not just be a rambling maniac.. 

Anywho. The reason I did it was that as long as you have this as a requirement on the text message format side of things, I immediately see that as valuable meaning and we could carry it forward. I don't see a that we need to optimize it away. Unless of course they don't want the information and the text message format is just a short-hand and nothing else.

**Comment by karolikl** [comment]
@Velcrow81, the RC has not had any preferences on this, so we're free to use two separate events. Hearing @einari's arguments, I'm convinced :)

**Comment by Velcrow81** [comment]
Updated event names and properties in the Event overview project so they reflect the code

**Comment by karolikl** [comment]
I seem to have been mistaken in my previous comment. I just checked with RC and they only need over5/under5 (see complete comment here: https://github.com/IFRCGo/cbs/issues/45#issuecomment-344599168).

**Comment by Velcrow81** [comment]
So, do they get what they want? :)

**Comment by karolikl** [comment]
There are two options: 
1) Persist the single case reports (w/ age) so that we have it available should they need this information at some point, but display the reports as under5/over5 in the UI so that they don't see the age. 
2) Persist the single case reports as under5/over5 so that the specific age is lost. 

If the concern of the RC is that someone might be able to identify a person based on their location+age, then option 2 might be the best solution.

**Comment by einari** [comment]
Probably best to do the second and avoid any issues with it then. This could be changed in the future if they want and can get more detailed data.

**Comment by Velcrow81** [comment]
Cool. @einari: Can you then roll back the changes you made so we end up with emiting all CaseReportReceived as aggregate reports?

**Comment by einari** [comment]
I don't think I'll roll back. But we can fix the aggregate to have only one type and the message handler call the right methods on the aggregate.

Removing code always feels good - as long as we don't lose meaning of course :)

**Comment by Velcrow81** [comment]
Poor choice of words on my part😊 Remove code we don't need. Don't do a git rollback 😊

**Comment by Velcrow81** [comment]
Code removed :)

**Comment by Velcrow81** [comment]
Added public string Origin { get; set; } to record the number that was used to send a case report since a datacollector can have many numbers. This is needed to reply back to the same number used to send

**Comment by Velcrow81** [comment]
Changed the naming of age grouping to ensure there are no overlaps in ages. Before, it was not clear were the 5 year olds should go

**Comment by Velcrow81** [comment]
Changed back to Under5 and 5AndOver

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
