### ISSUE TITLE
NewPhoneNumberReceived

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#136]
VolunteerReporting might receive a SMS from a phone number that is not registered in the system. If so, the volunteer will be asked to supply their previously-registered phone number and this will be used to look up the correct user. 

**The event contains the following information:**
ID of the DataCollector
New phone number

**Comment by Molokai** [comment]
After discussing with John, Amanda and Anine, it was clarified that 

a) There is a security issue with having an unauthenticated phone being able to "add itself" to a volunteer
b) If a volunteer loses their only phone, they have bigger problems and might be unable to reconnect
c) some coordinator approval would be needed to fix the registration of the new phone number.

In sum, the update of a phone number like this is on the nice-to-have side, where adding a manual verification step to the process will complicate it and make the benefit of having an automated process rather small compared to a manual out-of-bound update of the phone number.

Therefore propose we DO NOT implement this event and the Lost Phone Procedure at this time.
