### ISSUE TITLE
ManualSMSSent

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#137]
Is this event needed?

**Comment by eprom** [comment]
@karolikl @Velcrow81 can we close this issue if the event not needed?

**Comment by Velcrow81** [comment]
Sounds like this can be deleted. I think we need another event that says something like data collector informed or something similar, but lets wait til we know what we need

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
