### ISSUE TITLE
ProjectCreated

### ISSUE THREAD

**Issue by mfredbo** [IFRCGo/cbs#138]
### Description
This alert is raised after a new project is created.

### Data
Id, ProjectName

**Comment by mfredbo** [comment]
@RFMoore Please would you assign this issue to the label "event" and project "Events overview".

**Comment by roarfred** [comment]
This event will need more properties. We had a discussion about the detail level of health risks for the project, and we see that we should have a reference to the health risk iten (Id), but also that some of these properties might be overridden per project. We will need to define which properties to allow override for. Right now we know of Treshold, but I think it was also mentioned that name could be a subject for this.

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events
