### ISSUE TITLE
DataCollectorRegistered

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#139]
Proposed eventproperties: ( Edit (@woksin 30.03.2018): Update fields and class name to match actual event) 
```
        public Guid DataCollectorId { get; }
        public string FullName { get; }
        public string DisplayName { get; }
        public int YearOfBirth { get; }
        public int Sex { get; }
        public int PreferredLanguage { get; }
        public double LocationLongitude { get; }
        public double LocationLatitude { get; }
        public DateTimeOffset RegisteredAt { get; }

```
PhoneNumbers will be added and removed through sepperate events. Same for email

**Comment by roarfred** [comment]
Assuming this is the same as a data collector, we should also have a geo location (lat/long) for the volunteer

**Comment by karolikl** [comment]
Correct, I've renamed it to DataCollectorRegistered and added lat/long to the property list above. 

When the Data collector is updated, will you emit the this event (if so, maybe we should rename to DataCollectorSaved or similar) or is an update a separate event (DataCollectorUpdated for example)?

**Comment by roarfred** [comment]
We (the admin team) are simply consuming these events, but will have to access the user's location. Someone from the user management team might have to answer about emitting, @cathinkaw ?

Regarding the granularity of the evnents (created vs created/updated vs created/nameupdated/locationupdated) etc, I am still a bit confused about. I will try to seek more information on such guidelines, maybe @einari has a good source?

**Comment by einari** [comment]
The granularity should be on a level of what has happened - and not in terms of CRUD operations. But things like you're saying, e.g. ProjectNameChanged.
Martin Fowler did a writeup on the pattern itself here: https://www.martinfowler.com/eaaDev/DomainEvent.html

http://verraes.net/2014/11/domain-events/

Getting to the events can use something called Event Storming: 
https://en.wikipedia.org/wiki/Event_storming
https://techbeacon.com/introduction-event-storming-easy-way-achieve-domain-driven-design

Good writeup here as well:
https://blog.redelastic.com/corporate-arts-crafts-modelling-reactive-systems-with-event-storming-73c6236f5dd7

There is also a lot of metadata collected around events, you'll find the details in the EventEnvelope that is saved:
https://github.com/dolittle/DotNET.SDK/blob/master/Source/doLittle/Events/EventEnvelope.cs

I will make an issue for me to include all the details I put here as a general documentation thing. Thanks for bringing it to my attention 👍

**Comment by karolikl** [comment]
I also see that the DataCollectorAdded event includes one phone number. A user might have several phone numbers registered, and we need all the phone numbers in Volunteer Reporting in order to identify who is sending SMS reports.

**Comment by Velcrow81** [comment]
Event proposal based on existing comments:
```
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public List<string> MobilePhoneNumbers { get; set; }
        public string LocationLongitude { get; set; }
        public string LocationLatitude { get; set; }
```
Thoughts? Do we need PrimaryPhoneNumber? 

Do we also need middle name? Or do we just adjust any names (either by omitting parts of it or putting more than one into either) to fit first or last name?

**Comment by einari** [comment]
Looks good - question is; could the phone number piece be a separate event - "PhoneNumberAdded". A comment on the use of List<> - if it is a collection of something, it should be either IEnumerable<> or just an array - its immutable. 
You should never expose mutability externally from any system - could cause unwanted side-effects.

**Comment by Velcrow81** [comment]
Fixed list to IEnumerable. It sounds like a good idea to sepperate phone number out from DataCollectorAdded event into sepperate events: PhoneNumberAdded and PhoneNumberRemoved. Both should need DataCollectorId and the phone number

**Comment by Velcrow81** [comment]
New proposal after Phone numbers have been moved to sepperate event:
```
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }        
        public string LocationLongitude { get; set; }
        public string LocationLatitude { get; set; }
```

**Comment by einari** [comment]
Looks good - are longitude and latitude double/decimal ?

**Comment by Velcrow81** [comment]
Not sure. This is based on the type that comes on text messages from the sms gateway. There, longitude and latitude are string values. Any thought on this @ravndal ? Should they instead be double/decimal?

**Comment by Velcrow81** [comment]
In the UserManagment project, this event is defined with some additional properties: 

        public int Age { get; set; } 
        public Sex Sex { get; set; } 
        public Language PreferredLanguage { get; set; } 

Questions: 
1. Should age be date or year of birth instead? Maybe year of birth so we don't store to sensitive infomation. And do we really need to know their age?
2. Is it important to know the sex of a datacollector? Why do we need it? 
3. Both Sex and PreferredLanguage are enums, but they should be stored as primitive values. Should we store the values as string or int? I.e. Sex = "Male" or Sex = 0 (Male is the first enum value)

**Comment by Velcrow81** [comment]
Answer from @aninek : we need to know sex and age to ensure appropriateness of data collectors to what they are surveilling. Agree to YoB- as means updates wont be necessary.

Age should be renamed to YearOfBirth
@einari : Any thought on question 3?

**Comment by Velcrow81** [comment]
FirstName and LastName is changed to FullName and DisplayName after input from Michael:

Michael [2 days ago]
@anine   Is first name and last name the correct things to record?  Does this cover how people are named in all the countries we will be deploying to?


anine [2 days ago]
Hi! No, you are right! Some countries do not consider names like this. Suggestions for how to solve? Just 'name'?


Michael [2 days ago]
https://www.w3.org/International/questions/qa-personal-names

On the basis of this, I would suggest we follow the "Fullname" and "DisplayName" (What do we call you?) approach
w3.org
Personal names around the world
How do people's names differ around the world, and what are the implications of those differences on the design of forms, databases, ontologies, etc. for the Web?

**Comment by Velcrow81** [comment]
Removed public Guid NationalSociety from event since a DataCollector is always created within the context of a national society and since each national society is isolated from eachother, it is redundant information

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
