### ISSUE TITLE
Send in report data via SMS

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#152]
### Description
Data collector should be able to send rapport via standardized SMS. 
Requirements for report SMS to within 160 character limitation to keep costs for the data collector a low as possible

- max length of sms is 841 characters in the gateway

### Report types
Two types of reports: 
a) single case (EVENT,GENDER,AGE) 
b) aggregated (EVENT, # of cases, 4 categories (M<5, M>5, F<5, F>5)

### Things to keep in mind
- todays solution use # and * as a separator
- most newer feature phones have changed the # character button to _shift_ and _T9_ functionality when in SMS view, and the # has to be inserted via special character sheet (=complex)
- A new format with e.g. letters as separators might be more useful and should be user tested in the field

**Comment by aninek** [comment]
Given the difficult use of # in feature phones can we please explore using e.g. * or other as noted above

**Comment by alexanderhoset** [comment]
moved to https://trello.com/c/8xUFQdoK
