### ISSUE TITLE
Zero reporting

### ISSUE THREAD

**Issue by aninek** [IFRCGo/cbs#154]
Data collectors must be able to send a "zero report" when no health risks have been detected for one week. The zero report has the function of telling the system the data collector is still active, but all is fine. 

Format of SMS: 

|Health risk | sex | age |
|--- | --- | --- |
|0 | 0 | 0 |

**Comment by karolikl** [comment]
These should also receive a "Thank you for your report" message in return.

**Comment by karolikl** [comment]
To elaborate, a zero report should result in a standard case report (from either an anonymous or identified data collector), so this issue mainly consists of: 
- Writing test to verify that zero reports are stored as expected.
