### ISSUE TITLE
As a data coordinator, I want to be able to update all staff users

### ISSUE THREAD

**Issue by cathinkaw** [IFRCGo/cbs#155]
**Purpose:**
We need to be able to update the information saved on staff users.

Overview of fields that should be possible to change can be found here: #354

**Comment by cathinkaw** [comment]
There is no need to be able to delete users. Roxanne : "Rationale: We want to retain all contact information for a person to link with historical reports. We never want to have an SMS report without reporter info"

**Comment by roarfred** [comment]
Just sharing some experience... There might be reasons to at least hide people in the system. Could be people who's diseased, excluded etc. and there might be reactions from others seeing such names in there

**Comment by karolikl** [comment]
Update: Deletion is already implemented.

**Comment by karolikl** [comment]
No longer valid as staff users are handled by dolittle.
