### ISSUE TITLE
Respond to a feedback-SMS via SMS

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#156]
### Description
Dependent on the type of feedback SMS – e.g. a question – the data collector should be able to send a reply via SMS. This reply should follow a format that is decided upon

### Things to keep in mind
- The data collector has to be trained / informed about the format of the reply
- This might be able to compensate be complexes parsing of human action on messages by other roles of the system

**Comment by alexanderhoset** [comment]
Moved to  https://trello.com/c/k6YLyqCp
