### ISSUE TITLE
Register data collectors

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#158]
### Description
A user of the system with the corresponding user rights should be able to register new data collectors through the web interface. 

- If all required fields are provided, the registration can be completed by that user. 
- If not all fields are provided, but an email address for the invitee is present, a ticket to verify and self-complete the registration should be send to the invitee.
 _This behaviour will in many cases not be currently applicable because of limited access to the internet and knowledge. But since this behaviour will be needed for all other user registration flows, if should be considered not to limit it here._

### Environment
The user registrating data collectors will mainly use mobile devices to complete the registration (tablet/smart phone) with internet access (Wi-fi, 3G etc.) in the field (aka under stress). The web interface should be intuitive and optimised for these devices. 

### Things to keep in mind
- In particular the GPS location field is important to be filled in as easily as possible. 
- To make it as accurate as possible different options to provide the GPS information should be provided 
-- Read from device sensor
-- Pin on map (which one? native from device? specific map?)
-- Manual by numbers (three fields)
- We need support for a multi-language GUI,
-- use case include that the user that is registering a data collector in the field, can communicate the information on the screen in a language they understand.

**Comment by hodoea** [comment]
![open-map](https://user-images.githubusercontent.com/8971560/31054124-0be029d6-a6ac-11e7-9de7-04625a9f98db.png)
Some rough sketches
![1-version](https://user-images.githubusercontent.com/8971560/31054123-08576ea0-a6ac-11e7-83d5-1a251b68ef52.png)

**Comment by alexanderhoset** [comment]
Needs to be combined with #65 and #64 and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/2jkmQSBm
