### ISSUE TITLE
Edit data collectors

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#160]
### Description
A user of the system with the corresponding user rights should be able to edit the user information of data collectors through the web interface.

### Environment
The users editing data collectors will mainly use mobile devices to complete the registration (tablet/smart phone) with internet access (Wi-fi, 3G etc.) in the field (aka under stress). The web interface should be intuitive and optimised for these devices.

**Comment by alexanderhoset** [comment]
moved to https://trello.com/c/oskuUDhY
