### ISSUE TITLE
View and configure KPI's on dashboard

### ISSUE THREAD

**Issue by EvyTurk** [IFRCGo/cbs#163]
### Description
Data consumers can be local communities, regional/national authorities, multiple countries, technical/research institutes or other organizations).  They need to have access to different levels of the reports, which they can use for analysis and benchmarking, and response. They need to be able to choose the KPI's they would want to review or have the rights to view. 

- Requests:  
-- map with a sliding time scale and the number of reported cases over time (time frame of the information). Location to be linked to Red Cross branches (areas of operation). 
 -- button to create a pdf of the report 
-- button to print the report 
The viewer of the report needs to adjust the time (day, week, month), location (district/country level). 

### Environment
Web interface

![data consumer needs](https://user-images.githubusercontent.com/32349597/31053290-b3220d3e-a69a-11e7-865b-8df201224b8d.jpg)

**Comment by alexanderhoset** [comment]
Need to be combined with #85 and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/gGj2eJMI
