### ISSUE TITLE
Assign users to a region

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#167]
### Description
A user of the system with the corresponding user rights should be able to assign others (data collectors, data verifiers) to a region.

**Comment by roarfred** [comment]
This spans across the project setup in admin and create user in user management. Might be covered by other issues

**Comment by alexanderhoset** [comment]
These issues are here to keep an overview at product level for the product owners/designers. and yes will be delivered by multiple other issues

**Comment by alexanderhoset** [comment]
covered in the intended state by #171
