### ISSUE TITLE
Create case report for known phone numbers

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#172]
If a text message is received from a phone number that exists in our data collector store, the name and ID of the data collector should be included in the case report. When the case report has been created, a "CaseReportCreated" (#133) event must be emitted. 

**Further information**
- A data collector can have multiple phone numbers, so we need to check all of them. 
- We know that a text message has been received by listening to and [processing](https://github.com/IFRCGo/cbs/blob/master/Source/VolunteerReporting/Read/TextMessageRecievedFeatures/TextMessageReceivedEventProcessor.cs) the "TextMessageReceived" event.

Path to solution: https://github.com/IFRCGo/cbs/tree/master/Source/VolunteerReporting

**Comment by Velcrow81** [comment]
I will omit the name of the data collector since the "CaseReportRecieved" (#133) have been proposed to only keep the Id of the DataCollector

**Comment by karolikl** [comment]
Is the case report stored in the db after it has been processed?

**Comment by Velcrow81** [comment]
Nope. Just the event. But I can make it happening 😊

16. okt. 2017 21:41 skrev "Karoline Klever" <notifications@github.com>:

**Comment by karolikl** [comment]
I created a new issue for storing the case reports: #234
