### ISSUE TITLE
Emit SMSParseFailed event if parsing of incoming SMSs fail

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#174]
If an incoming SMS cannot be parsed as a single case report #44 or an aggregated case report #46: 

- Look up data collector based on the phone number and persist the message together with name and ID of datacollector (into a dead letter store)
- Emit an TextMessageParsingFailed event

**Comment by Velcrow81** [comment]
Is it important to save the name of the datacollector? From what I understand, the name is not relevant for the content of the text message and the Id of the datacollector should be enough to identify the datacollector later if needed. Thoughts?

**Comment by Velcrow81** [comment]
Also, what if the datacollector is unknown and the parsing failes? Should we parhaps add a new event called SMSParseFailedForAnonymousDataCollector?

**Comment by karolikl** [comment]
The name is not needed as long as we have the Id, having it there will simply cause more work (with updating name etc). So feel free to drop it :) 

About the new event, I think having a separate event is a good idea, but can we call it something else? Since we use TextMessageParsingFailed for the known data collectors, what about TextMessageParsingFailedAnonymous for example?
