### ISSUE TITLE
Consider simpify and breaking apart the "wizard"

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#179]
### Description
The data entry process for starting a new project is fairly complicated, it involves many people and interaction with several external systems.

In order to simplify the process, and to make it easier for parallel tasks by different users, the following is proposed:

* Make the "New Project" page the only page necessary for creating a new project (Ref #35)
* Let the project be created in a "Not Started" state
* Have the other pages available as separate places to assist the completion of the project setup (Ref #37, #54, #62)
* Use a visual indicator to present a task list of the necessary tasks to perform before going live with the project, and a "Go live" button that can kick the project to life.

**Comment by alexanderhoset** [comment]
Needs to be combined with #35, #37, #54,#62 171 and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/DIzoOZ9Y
