### ISSUE TITLE
Receive case report feedback

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#180]
### Description
A data collector will receive feedback from the system based on the data he has reported via SMS. 
Different cases of feedback depending on type of data and situation: 

Know person 
- Known Data collector sends in valid single case report
- Known Data collector sends in valid aggregate case report
- Known Data collector sends in valid Zero report
- Known Data collector sends in invalid SMS message
- Known Data collector sends in 5 invalid SMS messages
- Known Data collector sends in two identical SMS messages with same time stamp
- Known Deactivated Data collector sends in valid case report

Unknown person
- Unknown sends in valid single/aggregate/zero case report
- Unknown sends in invalid SMS message

### Environment
SMS mostly received on feature phones in the field.

### Things to think about

**Comment by roarfred** [comment]
Would it make any sense to allow adding a #mynumber behind a message, to allow for reports from a borrowed phone? Dependent on the level of security we need, but if corect reports from unknown numbers really is an issue, this could be a middle way

**Comment by alexanderhoset** [comment]
@roarfred you are correct, and it is covered by  Unknown sends in valid single/aggregate/zero case report, the tech for this in #136  

I will map all use-cases to events soon

**Comment by alexanderhoset** [comment]
Needs to be combined with #69 and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/xD69Q6M9
