### ISSUE TITLE
Setup case report feedback messages

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#181]
### Description
A user with the required user rights has to be able to edit the content of several predefined feedback messages, based on language and project for the following use cases: 

Know person 
- Known Data collector sends in valid single case report
  - _(includes details of report + key message)_
- Known Data collector sends in valid aggregate case report
  - _(includes details of report + key message)_
- Known Data collector sends in valid Zero report
  - _(multiple messages, send random version)_
- Known Data collector sends in invalid SMS message 
- Known Data collector sends in 5 invalid SMS messages 
  - #177 backend
- Known Data collector sends in two identical SMS messages with same time stamp
- Known Deactivated Data collector sends in valid case report
  - _feedback to get reactivated_
  - _feedback to data verifier_

Unknown person
- Unknown sends in valid single/aggregate/zero case report
  - _inform they must be registered_
  - _feedback to data verifier_ 
- Unknown sends in invalid SMS message

### Environment
web interface

**Comment by alexanderhoset** [comment]
UI design for this is #202

**Comment by alexanderhoset** [comment]
needs to be combined with #71  and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/0zUBVQST
