### ISSUE TITLE
Send manual feedback messages

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#185]
### Description
A user of the system with the corresponding user rights should be able to send one-time feedback messages in bulk to a set of users based on different criteria: 

- Project
- Country
- Region
- Individual users

### Environment
web interface

### Things to think about 
Is there a use case for selecting a region by map and send feedback to all users registered within the selected location?

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/McEiGfPt
