### ISSUE TITLE
Create reports

### ISSUE THREAD

**Issue by krautmac** [IFRCGo/cbs#187]
### Description
A user of the system with the corresponding user rights should be able to create reports based on different criteria: 

*TODO* 
Find out the criteria you can choose from

### Environment
web interface

### Things to think about 
- Manual reporting vs sheduled reports
- Relation to operation dashboard
- Relation to export og data

**Comment by alexanderhoset** [comment]
Need to be combined with #84, #85 and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/KO2a55wp
