### ISSUE TITLE
Structure for documenting projects

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#196]
I'd like a way to structure documentation of user actions (Commands), information kept inside the project (at aggregate levels) and what information is being signaled to the other projects (Events).

Started on a very simple thing on our [project fork](https://github.com/admin-cherry-on-top/cbs/blob/master/Documentation/Projects/Admin/index.md), but I am not sure if this is what we intended the documentation folder for... Would need some input if this is worth pursuing or not.

**Comment by karolikl** [comment]
Great idea! I really like the format that you have created, so I would be very happy if each project would follow your lead!

**Comment by einari** [comment]
Looks really great..  
Is the Aggregate you've put in the ReadModel?

Love that you have identified an aggregate - after this week you'll have [AggregateRoot](http://www.dolittle.io/Backend/aggregate_root.html) to play with as an [EventSource](http://www.dolittle.io/Backend/Events/event_sourcing.html) for the Write side of things.

**Comment by roarfred** [comment]
I am a total novice with regard to terminology... I thought having one document do a more complete description of an object, including child objects which are manipulated through it. Could this be an aggregate root? (e.g. a project has a name, but also a list of health risks, and associations of data collectors to various locations. I thought it might be easier to keep our domain experts close if we do it like that)

**Comment by roarfred** [comment]
ok, I'll try to fill in some more, and see if we can have some domain experts say if it makes any sense

**Comment by roarfred** [comment]
More stuff added now, there's a [Command](https://github.com/admin-cherry-on-top/cbs/blob/master/Documentation/Projects/Admin/Commands/CreateProject.md), an [Aggregate](https://github.com/admin-cherry-on-top/cbs/blob/master/Documentation/Projects/Admin/Aggregates/Project.md) and an [Event](https://github.com/admin-cherry-on-top/cbs/blob/master/Documentation/Projects/Admin/Events/ProjectCreated.md)

How should I proceed? Are we ok with pull requests at this level, and then collect comments, or should I hold on to my own fork until stuff is more complete?

**Comment by einari** [comment]
Looks great. Create a PR - relate it to this issue and when it's in you can announce it on Slack.

**Comment by roarfred** [comment]
Announced in Slack (#general) now
