### ISSUE TITLE
CaseReportFromUnknownDataCollectorReceived

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#215]
Proposed properties:

public Guid CaseReportId{ get; set; }
public Guid HealthRiskId { get; set; }        
public string Origin { get; set; }
public DateTimeOffset Timestamp { get; set; }
public int NumberOfMalesUnder5 { get; set; }
public int NumberOfMalesAged5AndOlder { get; set; }
public int NumberOfFemalesUnder5 { get; set; }
public int NumberOfFemalesAged5AndOlder { get; set; }
public string Longitude { get; set; }
public string Latitude { get; set; }

**Comment by Velcrow81** [comment]
Updated name because of input from @einari in #245.

**Comment by Velcrow81** [comment]
Updated because of discussion in #133

**Comment by Velcrow81** [comment]
See CaseReportRecieved on reasoning for change in age group naming

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
