### ISSUE TITLE
Build container images automatically.

### ISSUE THREAD

**Issue by sheeeng** [IFRCGo/cbs#218]
Use official accounts to setup Docker Hub to build container images automatically when:
- [ ] upstream base container image is updated.
- [ ] [Dockerfile](https://github.com/IFRCGo/cbs/blob/master/Dockerfile) in the project is updated.

The [dranoel/cbs-devel](https://hub.docker.com/r/dranoel/cbs-devel/) container image can be hosted in similar manner with official accounts.

Consider separate container images as `cbs-devel`, `cbs-runtime`, etc. for its purpose.

**Comment by eprom** [comment]
@karolikl can we close this issue?
