### ISSUE TITLE
PhoneNumberAddedToDataCollector

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#219]
When a Phone number is added to a data collector, a PhoneNumberAdded should be emitted:

```
        public Guid Id { get; set; }
        public Guid DataCollectorId { get; set; }
        public string PhoneNumber { get; set; }
```

**Comment by Velcrow81** [comment]
@einari : Should the names be more specific? PhoneNumberAddedToDataCollector and PhoneNumberRemovedFromDataCollector

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
