### ISSUE TITLE
PhoneNumberRemovedFromDataCollector

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#220]
When a phone number is removed from a datacollector, a PhoneNumberRemoved event should be emitted:

```
       public Guid Id { get; set; }
        public Guid DataCollectorId { get; set; }
        public string PhoneNumber { get; set; }
```

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
