### ISSUE TITLE
Generate test data to populate Health Risks

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#226]
In VolunteerReporting: 

- Generate a test data file for Health Risks (based on the information found here: https://docs.google.com/spreadsheets/d/1bfbfaTr6jx3ia7tOEZxDMDk-qrWAfS9vCoH2N-TG9zM/edit#gid=0) 
- In /Source/VolunteerReporting/Web/TestDataGeneratorController.cs, create a new method which emits a HealthRiskCreated event per Health Risk in the test data file. For inspiration, take a look at the CreateDataCollectors() where something similar is done for Data Collectors.

**Comment by roarfred** [comment]
This spreadsheet has been parsed into a json (containing HealthRiskCreated events), here: https://github.com/IFRCGo/cbs/blob/master/Source/Admin/Web/TestData/HealthRisks.json

**Comment by roarfred** [comment]
A solution for this is included in PR #228

**Comment by roarfred** [comment]
This was lost and needs to be fixed (probably caused by me working on different branches, committing incompatible work for others to fix)
