### ISSUE TITLE
Switch to xUnit in VolunteerReporting

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#233]
Instead of using Microsoft.VisualStudio.TestTools.UnitTesting, we'd like to use xUnit in VolunteerReporting. 

Also, unit tests should be moved to a separate project (example https://github.com/IFRCGo/cbs/blob/master/Source/VolunteerReporting/Web/Features/CaseReportReceptionFeatures/TextMessageContentParserTests.cs)

Summary: 
- Switch to xUnit
- Move tests to separate project

**Comment by roarfred** [comment]
Should all test projects be in a separate folder Tests, at the same level as the folders Domain, Events, Read etc? Or do we want the test projects inside each one project folder?

**Comment by karolikl** [comment]
I feel as though this is a question of preference, so you decide :)

**Comment by roarfred** [comment]
ok, going for a structure like this:
* Domain
* Events
* Read
* Web
* Tests
  * Domain.Tests
  * Events.Tests
  * Read.Tests
  * Web.Tests

Got an empty set up for the web project. Also included the xunit.runner.visualstudio, to get IDE integration

PR coming up in a moment

**Comment by roarfred** [comment]
Appveyor didn't quite like this... There's some documentation on this here, saying there's [a way around by running as a test script](http://help.appveyor.com/discussions/problems/6501-systeminvalidoperationexception-unknown-test-framework-could-not-find-xunitdll-v1-or-xunitexecutiondll-v2)

From log:
> Discovering tests...OK
>%xunit20%\xunit.console.x86 "C:\projects\cbs\Source\VolunteerReporting\Tests\Web.Tests\bin\Release\netcoreapp2.0\Web.Tests.dll" -appveyor
> xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
> System.InvalidOperationException: Unknown test framework: could not find xunit.dll (v1) or xunit.execution.*.dll (v2) in C:\projects\cbs\Source\VolunteerReporting\Tests\Web.Tests\bin\Release\netcoreapp2.0
> Command exited with code 1

**Comment by roarfred** [comment]
Should I make similar test projects for the other projects (Domian, Read etc)?

**Comment by anderaus** [comment]
(Alternatively disable auto-discovery of tests in appveyor and instead execute all tests from the cake script, making the entire CI setup more portable/migratable <- is that even a word?)

**Comment by karolikl** [comment]
Even better! We already have an issue for running tests from cake: #242.
