### ISSUE TITLE
Persist case reports

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#234]
All case reports created from incoming text messages should be persisted within VolunteerReporting (both anonymous #170 and from known senders #172). 

As we are emitting a CaseReportRecieved event and an AnonymousCaseReportRecieved event, we could create two event processors where we capture our own events and store the contents of the case reports in MongoDB. 
Anonymous and known case reports should be stored separately.

**Comment by roarfred** [comment]
Can/should we rely on our text message processor code to provide test data for case reports too?

**Comment by Velcrow81** [comment]
It says that "Anonymous and known case reports should be stored separately", but from what I can see, they are stored together. The anonymous reports are stored with DataCollectorId = Guid.Empty and the PhoneNumber is not stored. It will be difficult to identify anonymous reports if they all have an empty id and no phone numbers to check against

**Comment by roarfred** [comment]
Agree, my bad! I assume there will be separate read models and logic handling these all the way to the UI too, then?

**Comment by Velcrow81** [comment]
I also assume that😊

20. okt. 2017 07:55 skrev "Roar Fredriksen" <notifications@github.com>:
