### ISSUE TITLE
Create API endpoint: GET api/casereports/

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#235]
Should GET all casereports from MongoDB.

**Comment by karolikl** [comment]
Note: This issue is dependent on #234.

**Comment by roarfred** [comment]
Just noticed :) I'll include event processing/storage and sample data, unless someone beats me to it...

**Comment by roarfred** [comment]
Ref #234, as there is requested separate storage for anonymous reports, we might need to also have two separate API endpoints for the two types of case reports?

**Comment by roarfred** [comment]
In #239, we are describing that the page listing case reports should also show reports where parsing failed. This means there will have to be event processor, read model and API for the two types of InvalidCaseReports (is it InvalidReport or InvalidCaseReport?)

@alexanderhoset, this should include what you were asking for
