### ISSUE TITLE
List of case reports

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#239]
Description

Design a list of case reports based on bootstrap components, that includes:

- List all case reports 
- Filter based on message status

**Comment by karolikl** [comment]
The following types of case reports have to be included:
- Case reports that were correctly processed, from a known data collection 
- Case reports that were correctly processed, from an unknown  data collection 
- Case reports that could not be processed, from a known  data collection 
- Case reports that could not be processed, from an unknown  data collection 

Whether they are displayed in one list with filters or separate lists based on the type of report is something you need to consider. Also whether they should be grouped somehow (either by success/failure of processing or by known/unknown data collector).

**Comment by alexanderhoset** [comment]
design for mvp added to ux slack

**Comment by alexanderhoset** [comment]
![case reports](https://user-images.githubusercontent.com/11355331/32738342-d90e0f24-c89c-11e7-842d-d1595c2d85b6.png)

**Comment by alexanderhoset** [comment]
See design/cbs.pdf
