### ISSUE TITLE
List of case reports

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#240]
In Source/VolunteerReporting/Web.Angular project: 
Create UI showing a list of case reports. 

API endpoint: GET /api/casereports

Note: The design has not been implemented yet (#239), so do not spend time optimizing the UI. Simply showing the data is enough in this case.

**Comment by roarfred** [comment]
Fixed by #247

**Comment by alexanderhoset** [comment]
#239 now has a design mockup

**Comment by woksin** [comment]
This is considered done, right?
I suggest closing it.
@karolikl 
@alexanderhoset
