### ISSUE TITLE
Failing build for User Management

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#262]
Front-end build failing: 
https://ci.appveyor.com/project/karolikl/cbs-83l5k

**Comment by anderaus** [comment]
Fixed in #264. Reason for this suddenly starting to fail is that the project is using a beta version of Material 2 for Angular (instead of Bootstrap). Material 2 recently deprecated the `md`-prefix.
Reference: https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix
