### ISSUE TITLE
Failing build for Admin

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#263]
Front-end build failing for Admin: 
https://ci.appveyor.com/project/karolikl/cbs-xxsg0

**Comment by anderaus** [comment]
Weird. Tested by building the Admin project from my up-to-date fork on AppVeyor and everything is green.

**Comment by karolikl** [comment]
That's really strange! I set up a build in AppVeyor for Admin towards my own fork and that is also green. Must be something with the config in AppVeyor towards the inrcgo repo then, I'll have a look.

**Comment by karolikl** [comment]
Deleting the project and recreating it in AppVeyor did the trick.
