### ISSUE TITLE
Commits to the Example project do not trigger a new build

### ISSUE THREAD

**Issue by anderaus** [IFRCGo/cbs#270]
@einari merged #266 at 15:29, however at 15:43 it has still not triggered a new build of the Example project. Ref: https://ci.appveyor.com/project/karolikl/cbs-hjk90/history

**Comment by karolikl** [comment]
The webhook for the Example project and the VolunteerReporting project had not registered with GitHub. I've not registered them manually, let's see if that helps.

**Comment by karolikl** [comment]
Looks like this is working now.
