### ISSUE TITLE
Get and update automatic reply messages

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#274]
In Volunteer Reporting, the automatic replies in issue #273  should be editable by the data manager. 

- The messages should have a default/pre-populated value (where should this come from? Admin?).  
- API endpoint needed with a GET and a PUT to retrieve and update the automatic replies.

**Comment by alexanderhoset** [comment]
Point one is the following 
We need two lists of automatic reply messages: 
-System wide fallback
-Project

**Comment by alexanderhoset** [comment]
as I see it the endpoint need:
project id
event 
language code 
message

**Comment by roarfred** [comment]
From #273, I see there are four types of reply messages:
* Unknown sender
* Invalid report (known sender)
* Zero incidents
* One or more incidents

How dynamic do we see these? Do we want to hard-wire the API for these types, open for a more extendable approach using an type/enum, or anything more flexible where rules are defined per project?

I assume a good start can be going for the middle way here, and that "event" as described by @alexanderhoset is the type/enum. As such, we can have the following routes: (also indicated in #275)

GET /api/automaticreply (all messages, for all projects, all languages)
GET /api/automaticreply/{projectId} (all messages for specific project, with defaults from admin/fallback)
PUT /api/automaticreply (only for project specific messages, fallbacks are handled by admin project)

Not sure if the first one is even needed, will the same data manager be working across projects?

**Comment by alexanderhoset** [comment]
My idea is the following(for MVP):
For reporting
1. When a project is created we call getautomaticreply from admin. This adds the fallback messages to the project and the context treat team as project specific messages, . 
2 . All adds or edits are project specific.

for admin 
Get & put automaticreply

**Comment by karolikl** [comment]
Great discussions! One important thing to remember here is that all communication between bounded contexts is done by events, which means that when a project is created from admin, we need the event that is emitted to contain the default reply messages. These will then be stored in VolunteerReporting, and can be overridden by the Data Verifyer in the project. 

I think the endpoints described by @alexanderhoset looks like the right way to go. Of course, the two first are in Admin, so I have created a separate issue for these: #303.

**Comment by karolikl** [comment]
On a second thought: As the automatic replies are only used in VolunteerReporting, maybe the correct solution is that the default messages should also be created/updated there?

**Comment by alexanderhoset** [comment]
its best to split as an admin are not down on project level. it will be the same GUI

**Comment by alexanderhoset** [comment]
I see this  types of reply messages for the MVP:

- Unknown sender
- Valid report
- Invalid report (known sender)
- Zero incidents
- One or more incidents

- Key message(example "remember to wash your hands ") that can be included in all scenarios.

**Comment by roarfred** [comment]
Is there any documentation, or good examples on how we pass an enum value from events to read model and out through the API to the UI?

**Comment by roarfred** [comment]
@alexanderhoset, don't you agree that "Zero incidents" and "One or more incidents" will cover the "Valid Report"? I thought these messages should be mutually exclusive, or did we want to have the option for multiple replies?

**Comment by alexanderhoset** [comment]
after a phone call with @roarfred I agree that we are covered, so remove  Valid Report: 
the list 
- Unknown sender
- Invalid report (known sender)
- Zero incidents
- One or more incidents
- Key message(example "remember to wash your hands ") that can be included in all scenarios.

**Comment by roarfred** [comment]
Is there any thoughts on how we'd like to represent a language. I guess we'll go for a standard, but there's a few... Would there be any trouble going for RFC4646? (same as CultureInfo uses in .Net)
This way we'll get country-language, e.g. nb-NO, en-US etc. However, this is pretty fine-grained, so there is a difference between en-US and en-GB. Some places share a language between countries, and some have many laguages in the same country

**Comment by karolikl** [comment]
Good question! I have never used anything other than RFC4646, but I believe this is more of a question of whether this poses any issues for the RC. 

@aninek, have you discussed any standard for languages?

**Comment by roarfred** [comment]
According to #69, the key message is not a general per project text, but per health risk (referred as event there). It doesn't say much if this is to be a per-project overrideable or not. Any thoughts on this, or should we try to get some more info from the domain experts?

**Comment by karolikl** [comment]
You are right, the key message is not defined per project, but per health risk and there has not been any mentions of project overrides on this. So I think we can safely assume that this comes from the health risks (but feel free to check the ##domainexpertquestions channel on Slack if you'd like to be 110% sure).

**Comment by alexanderhoset** [comment]
Thanks for the clarification 
We still need to be able to insert {{keyMessage) in to the messages  per project.

**Comment by roarfred** [comment]
From the ##domainexperts, it is clear that we want the key message and key action to be per health risk. Still with a global default, and overridable inside the project.

Proposal:
* New read model for DefaultAutomaticReplyKeyMessage and AutomaticReplyKeyMessage
* New events for defining these (default from Admin, and the other from VR)
* Key Message and Key Action can be distinguished by a type enum (allowing for future types)
* New API endpoints to read/modify the per project overrides in VR
* Some UI to manage the project overrides (not sure if this is already defined, @alexanderhoset?)

@karolikl, can you please confirm if I'm on the right track here?

**Comment by alexanderhoset** [comment]
Some UI to manage the project overrides : #275 can be used for both keymessage and and feedback messages,
I will update the drawings

**Comment by karolikl** [comment]
@roarfred, you are definitely on track. Great work!

**Comment by alexanderhoset** [comment]
#175 updated to handle keymessage

**Comment by Velcrow81** [comment]
@roarfred: During the last codeathon, it was decided that for now, reply messages will only be laguange specific. They will not depend on project. Right @karolikl ?

**Comment by karolikl** [comment]
Sounds right! I've created a separate issue for this: #507
