### ISSUE TITLE
Generate test data for projects

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#279]
In /Source/Admin/Web/TestData:
Generate a test data file for Projects, so that we are able to prepoulate the database with some test data.

In /Source/Admin/Web/TestDataGeneratorController.cs, create a new method which emits a ProjectCreated event per project in the test data file. 

For inspiration, take a look at the CreateHealthRisks() where something similar is done for Health Risks.

**Comment by roarfred** [comment]
Might be a good source to fetch some realistic data: https://reliefweb.int/updates?source=1242
(also supports filters and an rss feed)

**Comment by roarfred** [comment]
This seems to be solved now
