### ISSUE TITLE
Failing alert build after doLittle merge

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#281]
Build FAILED.

"C:\projects\cbs-q2clx\Source\Alert\Alert.sln" (Build target) (1) ->

"C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj" (default target) (9) ->

(CoreCompile target) -> 

  AlertMessages\AlertFeedbackService.cs(4,7): error CS0246: The type or namespace name 'Infrastructure' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  CaseReportPolicy.cs(6,7): error CS0246: The type or namespace name 'Infrastructure' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  AlertMessages\AlertFeedbackService.cs(14,32): error CS0246: The type or namespace name 'Feature' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  AlertMessages\AlertFeedbackService.cs(18,26): error CS0246: The type or namespace name 'IEventEmitter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  AlertMessages\AlertFeedbackService.cs(21,107): error CS0246: The type or namespace name 'IEventEmitter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  CaseReportPolicy.cs(14,37): error CS0246: The type or namespace name 'IEventProcessor' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  CaseReportPolicy.cs(16,32): error CS0246: The type or namespace name 'Feature' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  CaseReportPolicy.cs(19,26): error CS0246: The type or namespace name 'IEventEmitter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

  CaseReportPolicy.cs(24,59): error CS0246: The type or namespace name 'IEventEmitter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cbs-q2clx\Source\Alert\Policies\Policies.csproj]

    0 Warning(s)

    9 Error(s)

**Comment by roarfred** [comment]
Trouble here seems to be that the Policies project is dependent on processing and emitting events, still set up to use the pre-doLittle infrastructure.

I can see a solution where we make the Services in the Policies project AggregateRoots (adding a dependency to doLittle.Domain, or rather just moving these to the Domain project).

Then, the CaseReportPolicy is an Event Processor and after touching the read model, it needs to emit events. Just the same as discussed in length in #184

**Comment by einari** [comment]
I've put in a temporary fix - there will come a formalised building block for this soon. When that is in place, we'll have to go back and retrofit that.
