### ISSUE TITLE
Failing project builds after doLittle merge

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#282]
### Description
After the doLittle merge #272, solutions are not updated to include all necessary projects and build from VS will fail. Might be related to #281...

Go through solution files for all projects and ensure they will build

**Comment by roarfred** [comment]
Checked all solutions now. Seems to be only a problem with VolunteerReporting, except for Alerts which needs to be updated to use the doLittle infrastructure, as described in #281

**Comment by karolikl** [comment]
After merging PR #283, this works again. Great job!
