### ISSUE TITLE
Commands and properties from routing

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#289]
This might be a basic question, but I have a controller, which is used to set the health risk threshold (an int) for a specific health risk for a specific project.

The controller is having a routing scheme such as the project id and the risk id is passed in the url, while the  command itself is passed as the body of the request. Something like this:

```
[Route("api/projects/{projectId}")]
public class ProjectsHealthRiskController
{
  [HttpPost("healthRisks/{healthRiskId}")]
  public IActionResult SetHealthRiskThreshold(Guid projectId, Guid healthRiskId, [FromBody] SetProjectHealthRiskThreshold setHealthRiskForProject)
  {
  }
}
```

Now, for validation of the command, I can use the properties of the SetProjectHealthRiskThreshold object, but I would also need the projectId and the healthRiskId to be a part of this structure. Is there a secret way to do this, without requiring these properties to both be a part of the url and also be present in the body?

**Comment by einari** [comment]
Interesting. Question is if there is a call for a route like this or not. 
If the routing serves a purpose and this is a pattern we see emerge for other scenarios as well. We could have a generic `ActionFilter`that looks at properties coming in and see if can match it and amend the command before validation kicks in with the details. 

Another option, but this would require a bit more research would be to see if we could get rid of having the arguments (projectId, healthRiskId), but it automatically took the route values and put it on the command and still be able to find the controller action and execute it. 

Back to the first question; do we have the need for these types of routes? Or is it ok to just have everything on the command and don't care about the API for routing. Simplifies it. Depends on the goal.

**Comment by roarfred** [comment]
Didn't think of that. The route was in the spec, I was just following orders ☺ Will check and reference back here
