### ISSUE TITLE
Events are not fired (from infrastructure)

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#299]
### Description
Just found that the restructuring of the VolunteersReporting project, where the new CaseReporting class of the Domain project is used to raise events causes some problems.

It turns out that none of the events passed to the Apply function of this class ever makes it back to any ICanProcessEvents implementation.

However, events passed to the Apply function of the BaseController class, does find their way through to the corresponding event processors.

The result of this is that no test data for CaseReports will be made. This can be seen by calling the api at /api/testdatagenerator/textmessages

### Environment
* Windows 10
* VS 2017

### Steps to recreate
1. Call the API at /api/testdatagenerator/textmessages
2. See no data generated for case reports

### Current behavior
* Any breakpoint in Process methods of Read.CaseReports.CaseReportEventProcessor will be hit
* No test data is generated for Case Reports

### Expected behavior
* Any breakpoint in Process methods of Read.CaseReports.CaseReportEventProcessor should be hit
* Test data is generated for Case Reports

**Comment by karolikl** [comment]
I wish all bug reports were as detailed as this! Great!

**Comment by einari** [comment]
I'm in a travelling vortex these days - but I'll get to it as soon as I can. Hopefully tomorrow afternoon. I see a window of opportunity.. 

And yes! Great report - its almost to the point I want to create more bugs. (don't worry; I will - but all for the wrong reasons)

**Comment by karolikl** [comment]
@einari, any updates on this?
