### ISSUE TITLE
Filter the Case Reports by status

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#302]
You should be able to filter the list of case reports in the following ways: 

- All: Displays all reports(AS-IS)
- Success All reports with dataCollector & healthRisk  
- Data error: reports with no healthRisk
- Unknown sender: reports with no dataCollector

**Comment by karolikl** [comment]
@alexanderhoset, should we have an additional filter called "Success" (or similar), in case they only want to view the successful messages and not the "data errors" or "unknown senders"?

![image](https://user-images.githubusercontent.com/5235776/32714130-b0f540b6-c84c-11e7-968c-981a2f0d14ca.png)

**Comment by alexanderhoset** [comment]
@karolikl Yes, we need a Success filter too 
Since we now load all reports from AggregatedCaseReportService in one go, I updated the issue to be a strait-forward filter on the ng-for loop we already have

**Comment by alexanderhoset** [comment]
![case reports](https://user-images.githubusercontent.com/11355331/32738342-d90e0f24-c89c-11e7-842d-d1595c2d85b6.png)

**Comment by fredrik-lundin** [comment]
Would you consider pulling in a third party data table of some kind? I see that both this issue and #304 could easily be fixed that way. Probably have other tables in the application that could use similar functionality too.

A custom implementation is obviously possible. But I was just wondering how you guys are thinking about this.

**Comment by karolikl** [comment]
Great question! This is something we have not discussed, would you mind elaborating on how pulling in a third party data table could work? The pros and cons?

**Comment by alexanderhoset** [comment]
I have wondered the same, but the examples I have seen are so complex(many features). @fredrik-lundin do you have one in angular 2-4 that is simple to limit the feature set of?

**Comment by fredrik-lundin** [comment]
@karolikl , @alexanderhoset 
A lot of the grids are indeed quite complex, and might be overkill for these simpler use-cases. I will look into if there are some examples of simpler grids that might fit this application better!

**Comment by alexanderhoset** [comment]
Based on rewritten user story https://trello.com/c/KO2a55wp : 

Date range - New
Status (success/failure) - As-is
Health risk - New
Location - New

New design with extended filters will be uploaded tomorrow :

**Comment by alexanderhoset** [comment]
![case reports 1](https://user-images.githubusercontent.com/11355331/33392314-fef9b192-d53b-11e7-875a-4746a9699433.png)
![case reports 2](https://user-images.githubusercontent.com/11355331/33392315-ff27532c-d53b-11e7-8b92-079925a0b72c.png)

**Comment by alexanderhoset** [comment]
Advanced filter filters moved to #334

**Comment by alexanderhoset** [comment]
@woksin ng2-table is worth a try

**Comment by woksin** [comment]
@alexanderhoset see #459
