### ISSUE TITLE
Default values for automatic reply messages

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#303]
The automatic replies in issue #273 should have default values defined in Admin, which can be overridden per project by the data manager.

- API endpoint needed with a GET and a PUT to retrieve and update the default values of the automatic replies.
- When the default reply messages are updated, an event needs to be emitted so that VolunteerReporting pick up on the changes.

**Comment by krok** [comment]
Project overrides have been removed from the MVP. Instead, we set the language used for the messages.
