### ISSUE TITLE
Sort the Case Report list

### ISSUE THREAD

**Issue by alexanderhoset** [IFRCGo/cbs#304]
You should be able to sort the list of case reports based on column(ascending, descending order)

**Comment by woksin** [comment]
I'm on this.

**Comment by woksin** [comment]
@alexanderhoset is this solved by pull request number #451?
The sorting can easily be expanded to sort on healthRiskId aswell

**Comment by alexanderhoset** [comment]
Yes I will close this, but will make a note to look at a more scalable fix

**Comment by woksin** [comment]
@alexanderhoset I agree.
Maybe it will be an idea to look into opensource projects that deals with this in a good manner.
@alexanderhoset For example https://github.com/valor-software/ng2-table
or https://www.npmjs.com/package/angular2-datatable

**Comment by alexanderhoset** [comment]
@woksin ng2Table is worth a try for #302 and #334 .... if it works for that use it for this one also

**Comment by woksin** [comment]
@alexanderhoset I will give it a look.
