### ISSUE TITLE
API endpoint to list events that can trigger automatic reply messages

### ISSUE THREAD

**Issue by alexanderhoset** [IFRCGo/cbs#306]
### Description
In the GUI for automatic reply messages(#275) that has a dropdown to select the event you want to trigger a message on. To populate this list, please create an endpoint for it

**Comment by alexanderhoset** [comment]
This dependent on #274.

**Comment by roarfred** [comment]
I think this one is covered by endpoint defined in #275:
GET /api/automaticreplies/automaticreplytypes -> get id and name for event types (dropdown in drawing)

**Comment by alexanderhoset** [comment]
correct!
