### ISSUE TITLE
InvalidReportRecieved

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#309]
public Guid CaseReportId { get; set; }
        public Guid DataCollectorId { get; set; }
        public string Message { get; set; }
        public IEnumerable<string> ErrorMessages { get; set; }
        public DateTimeOffset Timestamp { get; set; }

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
