### ISSUE TITLE
Read model for Projects

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#313]
We'll need a read model to store project information, as very much information is related to a specific project. 

**This will have to be done:**
- [x] Define the external events as defined in the Admin project
- [x] Create a read model for storing the essential data for Volunteer Reporting
- [x] Create the event processors to populate the read model
- [x] Create controller to produce some sample data (3-4 project will do)
- [x] Create controller to get a list of projects

**Comment by karolikl** [comment]
Volunteer Reporting should not know about Projects, closing this as no longer valid.
