### ISSUE TITLE
Use new ProjectInfoChanged event

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#323]
Ref #322, there will be a new event taking over from ProjectChanged in the admin project. (New one is ProjectInfoChanged)

When this new event is defined, we'll have to implement the use in the Volunteer Reporting project. As we are currenly just using a name and the Id of the project, this might be just a name change on the event.

Steps: 
- [ ] Event definition in External.Events
- [ ] Event processors in Read project
- [ ] Sample data in Web project (TestDataGeneratorController)

**Comment by karolikl** [comment]
Volunteer Reporting should not know about projects, closing this as no longer valid.
