### ISSUE TITLE
Setup CBS as an application in Azure AD - single tenant 

### ISSUE THREAD

**Issue by einari** [IFRCGo/cbs#328]
We need to create a single-tenant Web App on Red Cross tenant in Azure. 
This tenant would allow Red Cross users to log in with their own credentials.

Could we have claims on every user saying which national society (Tenant) they have access to. 
This is not the Azure AD tenant ID - but something that enables us to check for authorisation if a particular user in a bounded context has access to the national society it claims to have.

Would it be an idea to have Identity Server infront of all this and augment the tokens with more information and let UserManagement interact with this and provide the mapping between users and what national societies they have access to. 

See also #31, #327,  #510

**Comment by einari** [comment]
We need help from someone in the Red Cross organization that has admin access to the Azure Active Directory

**Comment by einari** [comment]
Since I don't have access into the RedCross.no tenants active directory - for obvious reasons :) I Made a writeup on how to do this and sent to @eprom

**Comment by eprom** [comment]
@einari can we close this issue?
