### ISSUE TITLE
Error: Property 'forkJoin' does not exist on type 'typeof Observable'.

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#329]
**ERROR in /src/Source/VolunteerReporting/Web.Angular/src/app/core/aggregated-case-report.service.ts (32,27): Property 'forkJoin' does not exist on type 'typeof Observable'.**

I receive this error message when trying to build a Docker image for VolunteerReporting: 
`PS C:\Users\karolikl\OneDrive\Redcross\code\cbs> docker build -t karolikl/cbs-volunteerreporting . -f .\Source\VolunteerReporting\Dockerfile`

It fails when reaching:
+RUN ["ng", "build", "--prod"]

**Comment by alexanderhoset** [comment]
You could try to import this way:
import {Observable} from 'rxjs/Rx';
instead of:
import {Observable} from 'rxjs/Observable';

Just a quick guess

**Comment by karolikl** [comment]
I've made it work by adding: 
import 'rxjs/add/observable/forkJoin'; 

But I have no idea if this is the preferred way of doing it or if there's something better...

**Comment by alexanderhoset** [comment]
Ref comment in code by @roarfred  that  code block needs be be reviewed .... 

@anderaus or @fredrik-lundin is there a better way to combine multiple json calls:
see comment in: /Source/VolunteerReporting/Web.Angular/src/app/core/aggregated-case-report.service.ts

**Comment by fredrik-lundin** [comment]
Regarding the import. If you import it like this:
`import { forkJoin } from "rxjs/observable/forkJoin";`

Then you can use forkJoin without the `Observable` in the code like this:
`forkJoin(...)`

If you import like this:
`import 'rxjs/add/observable/forkJoin';`

Then you use it like this:
`Observable.forkJoin(...)`

Regarding if there is a better way to combine multiple json calls - I don't see the problem with forkJoin in this case. What forkJoin is doing is executing all Observables in parallel, and then emits when all of them have returned something. So from what I can see in the code, it kind of matches with what you are trying to do.
