### ISSUE TITLE
New properties on HealthRisk

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#332]
On a HealthRisk, the ConfirmedCase, SuspectedCase and ProbableCase properties should be removed, and a new should be added: CaseDefinition (string). 

KeyAction (string) should also be added to the HealthRisk.

The CaseDefinition of a health risk should be editable on a global level and must therefore be included in HealthRiskController. There is no POST endpoint here at the moment, this needs to be created as part of this issue.

The CaseDefinition should also be editable on a project level and must therefore be included in ProjectsHealthRiskController.SetHealthRisks(...).

**Comment by Velcrow81** [comment]
Event under Surveillance (might need to find a better name since event is not very descriptive) should also be added. It says something about who or what the health risk relates to. Allowed values are Human, Animal, Environment, Pregnant woman. Unusual event covers all, so we might need a value called All? Or a list of things? What do you think @karolikl and @aninek ?

**Comment by karolikl** [comment]
Since my two commits (to my fork, not this repo), there have been massive changes to the Admin project. I'm therefore deassigning myself from the issue in case anyone wants to grab it before I have to time look into the merge conflicts.

**Comment by AG-83** [comment]
Not done: The CaseDefinition should also be editable on a project level and must therefore be included in ProjectsHealthRiskController.SetHealthRisks(...).

**Comment by eprom** [comment]
@AG-83 would you like to stay on this issue? Seems you have resolved this issue, could you make a PR?

**Comment by AG-83** [comment]
Hei,Yeah I will do that, and will join for Monday 9th of April. We have a project delivery soon and sorry couldn’t close the case and check in the codes sooner


Sent from Yahoo Mail for iPhone


On Saturday, April 7, 2018, 12:18 AM, Samson Gejibo <notifications@github.com> wrote:


@AG-83 would you like to stay on this issue? Seems you have resolved this issue, could you make a PR?
