### ISSUE TITLE
Edit and save a HealthRisk

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#344]
Ref cbs/Design/cbs.pdf ("Add Health Risk")
 
Note: the theme flatly is used today, this should be changed to custom bootstrap variables. Ref #353

**Comment by AG-83** [comment]
I am on it, can't assign it to myself

**Comment by karolikl** [comment]
@ronnydahl and @AG-83, would you like to stay assigned to this task or can I reassign it to someone else?

**Comment by AG-83** [comment]
Hei, I am joking the code evening tomorrow, I can try to finish it then. 🙂
Regards,Arezoo

On Monday, March 5, 2018, 8:10 AM, Karoline Klever <notifications@github.com> wrote:


@ronnydahl and @AG-83, would you like to stay assigned to this task or can I reassign it to someone else?

**Comment by eprom** [comment]
@ronnydahl and @AG-83, would you like to stay assigned to this issue? We are having a code evening on this Monday 9th April at Hausmannsgate 7.  Please join us if you can!

**Comment by SneX13** [comment]
@eprom is this done? Can we close the issue?
