### ISSUE TITLE
Add new user

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#351]
Today, there are two separate views for adding a user (cbs\Source\UserManagement\Web.Angular\src\app\dataCollectorManagement\dataCollector.component.html & cbs\Source\UserManagement\Web.Angular\src\app\staffUserManagement\staffUser.component.html). 
There should only be one "add user" modal view, where the fields change based on the user type selected. 

Ref "Add user" page in cbs/Design/cbs.pdf 

Note: Material design is used today, this should be changed to bootstrap. Ref #352

**Comment by cathinkaw** [comment]
@karolikl should the two types of users also be saved in the same collection with a type attribute? (in the current code there are two collections: one for dataCollectors and one for staffUsers)

**Comment by alexanderhoset** [comment]
I do not see a reason to keep them separate, unless you want a real users(people that login) vs collector. I vote for  same collection with a type attribute, as a collector may login in the future via web/app to submit report, see his/her stats etc

**Comment by karolikl** [comment]
I imagine they're separated out to two collections as the read models for the two roles have very different properties on them. But if we're able to add different read models to the same collection, then feel free to put them in one collection.

**Comment by karolikl** [comment]
Update after codeathon. Views for creating all roles except DataCollectors have been added. 

**Remaining work on this issue: View for adding DataCollectors.**
