### ISSUE TITLE
Clean up StaffUser (read models, commands, events)

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#354]
**Update after codeathon2018:**
We have started the work of splitting up the "staffUser" into the several roles described below.
Decisions made:
- We're keeping it down to one endpoint for all users, with the same command for all users.
- The validator for the addUser-command validates based on Role and validated which fields are relevant for which roles.
- Controller will send command into Aggregate Root
- Aggregate Root will split up into several separate events for the different users based on Role (work begun by @smithmx )

**Original description:**
The StaffUser read model (\cbs\Source\UserManagement\Read\StaffUser.cs) needs to be split up into separate user types: 

All roles have the following properties: 
- Full name (Mandatory, editable)
- Display Name (Mandatory, editable)
- Email address (Mandatory, editable)

**Admin**
- See above

**System Configurator**
- See above, plus
- Birth year 
- Sex (Optional, non-editable)
- National Society (Mandatory, editable) @RFMoore need to include IFRC GVA and CO and ICRC GVA CO
- Preferred language (Mandatory, editable)
- Mobile phone number(s) (Mandatory, editable)
- MobilePhoneNumberConfirmed boolean (always true for MVP) (automated)
- Assigned National Societies (Mandatory, editable)

**Data Coordinator**
- See above, plus
- Age (Optional, _may need to move to birthyear as to change over time_)
- Sex (Optional, non-editable)
- National Society (Mandatory, editable) OR IFRC or ICRC GVA, region or CO
- Preferred language (Mandatory, editable)
- Mobile phone number(s) (Mandatory, editable)
- MobilePhoneNumberConfirmed boolean (always true for MVP) (automated)
- Assigned National Societies (Mandatory, editable)

**Data Owner**
- See above, plus
- Birthyear (Optional, editable)
- Sex (Optional, non-editable)
- National Society (Mandatory, editable)
- Preferred language (Mandatory, editable)
- Mobile phone number(s) (Mandatory, editable)
- MobilePhoneNumberConfirmed boolean(always true for MVP) (automated)
- Position (free text, position within the NS) (Mandatory, editable)
- Duty station

**Data Verifier**
- See above, plus
- Birthyear (Mandatory)
- Sex (Mandatory, non-editable)
- National Society (Mandatory, editable)
- Preferred language (Mandatory, editable)
- GPS location / Location (area) (Mandatory, editable)
- Mobile phone number(s) (Mandatory, editable)
- MobilePhoneNumberConfirmed boolean (always true for MVP) (automated)
- Registration date (to be set automatically)
- Staff or volunteer 
- If staff: Job title 
- Organisation/Affilliation: (National Society) or other 
- If other: Specify 

**Data Consumer**
- See above, plus
- Location (area) (Mandatory, editable)
- Registration date (to be set automatically)
- Staff or volunteer 
- If staff: Job title 
- Organisation/Affilliation: (National Society) or other 
- If other: Specify

**Comment by Davlind** [comment]
@smithmx, are you currently doing this? If not I'll do it.

**Comment by karolikl** [comment]
Keeping this open as @smithmx is working on splitting up Aggregate Root into several separate events for the different users based on Role.

**Comment by woksin** [comment]
I will look into this.
Improve the Read-model and add events corresponding to each of the different kinds of StaffUsers.
Question: @karolikl, would it be beneficial to have a collection for each of the different StaffUsers, or combine them into one collection? In my opinion I think it would be beneficial to split up the construction and processing logic for each of the different kinds of StaffUser.

**Comment by Velcrow81** [comment]
What you need in the view decide how the read model should look. Ideally, you should get everything from one model

**Comment by woksin** [comment]
@Velcrow81 Great, I'll get to it. I think I'll make a solution similar to what you did with CaseReportForListing

**Comment by aninek** [comment]
- System coordinator changed to System configurator to align. 
- Removed GPS location for system config and data coord.
- National Society needs to be expanded to included IFRC GVA, Region, and CO and ICRC GVA, Region and CO for System configurator, data coord
For data verifier: 
-  staff or volunteer? 
- if staff: title
For data verifier and data consumer:
- Organisation/Affilliation: (National Society) or other 
- If other: Specify

**Comment by smithmx** [comment]
Related to #486

**Comment by karolikl** [comment]
@smithmx, can we close this?

**Comment by woksin** [comment]
@karolikl My opinion is that we can close this now
