### ISSUE TITLE
Clean up Data Collector read model

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#355]
-Allow for multiple phone numbers.
  -MobilePhoneNumberConfirmed  boolean (for MVP always true)

The following information is inherited from the user that creates the Data Collector: 
- National Society
- Project 

System data:
- Registration date
- Last report received

**Comment by Velcrow81** [comment]
Can a data collector only be part of one project?

**Comment by karolikl** [comment]
Update: A DataCollector should not have the projectId stored with it. 

In Admin (for a project), we will retrieve all DataCollectors location within a certain area. This means that DataCollectors can be part of multiple projects if needed.

**Comment by Velcrow81** [comment]
Excellent. Then this is done :)
