### ISSUE TITLE
Set last reported date

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#356]
When a SMS report is received from a data collector, the last reported data on the user must be set. This is done by emitting an event that the user management context must listed on.

**Comment by woksin** [comment]
In the CaseReportReceived event and InvalidReportReceived event there is enough information to store the given user's latest reported TextMessage.

Use  DateTimeOffset Timestamp to set the DateTime for the latest reported case.

**Comment by tksoftware** [comment]
I have started working on this

**Comment by Velcrow81** [comment]
@tksoftware : Were is the code for this issue? Is it correct that it is done?
