### ISSUE TITLE
Export Case Reports 

### ISSUE THREAD

**Issue by alexanderhoset** [IFRCGo/cbs#359]
Ref cbs/Design/cbs.pdf (" Case Reports export")
  
- Edit (woksin) added task list
- [x] Export to csv
- [x] Export to excel
- [x] Export to pdf

**Comment by woksin** [comment]
Do we want to combine all Case Reports into one table, or give the user the option to choose which subset of the case reports he/she wants?

**Comment by alexanderhoset** [comment]
subset, as in if you have applied a filter, that has to count 
so export the current list  with filter or not. Normally they will use the daterange filter before selecting export

**Comment by woksin** [comment]
@alexanderhoset On the coreteam sync you said that you would look into this export functionality, Should we assign this to you?

**Comment by jakhog** [comment]
What's the plan here, server-side or client-side?

**Comment by woksin** [comment]
@jakhog I don't know what the others are thinking, but personally I think that this should be a server-side job

**Comment by eprom** [comment]
I go with server side.

**Comment by aninek** [comment]
We need to include some geographical information beyond GPS lat-long in the MVP as there is no analytics/dashboard. Therefore, when data collector registration is updated, can we include in the export also 

- Region

- District

- Village
Linked to #695

**Comment by aninek** [comment]
Timestamp needs to be split in date and time also in export.

**Comment by karolikl** [comment]
Fixed by #687 and #695
