### ISSUE TITLE
Define new CBS project - form (page 2)

### ISSUE THREAD

**Issue by RFMoore** [IFRCGo/cbs#37]
**Purpose:**
As a project owner, I want to define _how_ (SMS reporting structure), _what_ (health risk), _where_ (admin boundaries), and _who_ (point of contact) for a new CBS project (part 2 of "Create a New CBS" - #35) that way the scope of the Project is clearly stipulated.

**Conversation:**
_How (what SMS reporting structure):_
The Project owner needs to identify how a Data Collection volunteer will be reporting per project (select one).  There are two options: "Single event reporting" (Number#Number#Number) #44 or "Daily aggregated reporting" (Number#Number#Number#Number#Number) #46 
* "Single event reporting" hint:  "Volunteer sends report after each event."
* "Daily aggregate event reporting" hint: "Volunteer sends report at end of each day."

_What (Health Risk):_
The project owner needs to select up to 5 Health Risk that will be affiliated with a CBS project (ie Health Risk that a Data Collector will be collecting information on).  This list is supplied here - Admin Bounded Context (#33). 

_Where (Location):_
The project owner needs select where the CBS project will be running (e.g. part of a country or whole of a country).  The baseline map information will be stored here (#42 )

_Who (Data Verifier)_
The project owner needs to assigns a Data Verifier (role) to cover a geographical region where a Data Collection Volunteer (role) will be working.  Contact Information for Data Verifiers (role) will come from the User Management bounded context. 

Examples of how Location and Assignment of Data Verifier can overlap.

Map format:
![img_2276](https://user-images.githubusercontent.com/8931230/31076810-4d81bcf8-a77c-11e7-85bf-527d7062358a.JPG)

Table  format:

| Admin Level | Location | Point of contact | phone number |
| ----- | ----- | ---- | ----- |
| 0 National | Sierra Leone | Fatmata Sannoh| +253 557832903 |
|  2 District | Bo | Abdullah Marah | +253 7263432903 |
|     3 Chiefdom | Bobo | Sarah Makenni | +253 557832875 |
|   2 District| Kenema | Felix Kenny | +253 6589832903 |
|     3 Chiefdom | Kenny | Benny King | +253 552832903 |

**Comment by roarfred** [comment]
What are the implications of choosing single event over daily aggregate? Is there a reason we want to limit the system to only allow for one type of reported incidents?

Also, is this a property of a project that might change during the lifetime of the project? If so, the answer to the above question might give a clue to what the process is, what needs to be done and who's affected.

**Comment by karolikl** [comment]
From a Volunteer Reporting perspective, it doesn't matter whether you send a single event or daily aggregate, we will accept either one and create a case report for it (regardless of which setting is chosen for the project). So I'm very curious to hear what this property is for as well!

**Comment by roarfred** [comment]
It would be useful to break this issue up into several more independent issues. I think the (what) Healt Risk is covered by #54. The "where" and "who" might be useful to cover in one issue, as there might not be any reuse of location information

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/DIzoOZ9Y
