### ISSUE TITLE
Set up a new web frontend for navigation bar

### ISSUE THREAD

**Issue by Virrum** [IFRCGo/cbs#373]
### Description
We need a navigation bar for navigating across the different solutions. This will also wrap them in so they will be precept as one solution.

**Comment by alexanderhoset** [comment]
footer string  idea that can be included in this wrapper

> code make with ❤️  by the [contributors](https://github.com/IFRCGo/cbs/graphs/contributors) with these [components](https://github.com/IFRCGo/cbs/network/dependencies)
