### ISSUE TITLE
Add links to the navigation bar and make it look pretty

### ISSUE THREAD

**Issue by Virrum** [IFRCGo/cbs#378]
### Description
Add links for each web application and make the bar look pretty. Only style what's inside the toolbar, don't touch anything outside it.

**Comment by alexanderhoset** [comment]
Where do I commit the logo svg?

**Comment by Virrum** [comment]
Hi, 
It can be added either under cbs/Source/Navigation/Web/src/ or cbs/Design :)

**Comment by alexanderhoset** [comment]
https://github.com/IFRCGo/cbs/pull/393 adds the svg

**Comment by karolikl** [comment]
We also need this dropdown to be a selector of National Socity instead of Project: 

![image](https://user-images.githubusercontent.com/5235776/36997501-1eb07088-20ba-11e8-8e6d-0540cf29db2f.png)
