### ISSUE TITLE
Determine how to provisision databases

### ISSUE THREAD

**Issue by chrfrenning** [IFRCGo/cbs#418]
### Description
We need to control the database environment for a new tenant, e.g. setting up locales, indices, etc.

### Current behavior
There is no automated provisioning of the database layer.

### Expected behavior
A standardized way using code or scripts to ensure the database is correctly configured.

**Comment by einari** [comment]
This is being worked on in Dolittle - [here](https://github.com/dolittle/DotNET.Fundamentals/tree/master/Source/Resources)

We can probably live without automatic provisioning till after the MVP.

**Comment by einari** [comment]
Referring to the issue in Dolittle [here](https://github.com/dolittle-platform/home/issues/13)
