### ISSUE TITLE
Parse an SMS containing a single case report

### ISSUE THREAD

**Issue by aninek** [IFRCGo/cbs#44]
In a non-outbreak context, as a volunteer I need to report if I have detected health risk in my area. 

Reporting format: 

Event # sex of case # Age of case  

|Event | Sex of case | Age of Case in years|
| ---- | ---- | ----|
| 1| 2| 12 |

Events are coded by numbers according #33 
Sex of cases is coded as Male=1, Female=2
Age of case is reported as age in years
Report example 1#2#12 = Cholera in female 12years

Related to #46 #45

**Comment by aninek** [comment]
Issue is for documentation only. Removed from project.

**Comment by terjetyl** [comment]
Code for parsing content added to Domain.TextMessageContentParser
