### ISSUE TITLE
Converting single case reporting to default aggregate case reporting format

### ISSUE THREAD

**Issue by aninek** [IFRCGo/cbs#45]
**Purpose:**
All text messages will be stored in #48 as "Original message".  Accurate volunteer reports will follow either of the two reporting structures:
* [Number] # [Number] # [Number] (two hash - single event #44 )
* [Number] # [Number] # [Number] # [Number] # [Number] (four hash - aggregate event #46)

We want to map how two hash reports fit into the the four hash database.

**Conversation:**

|Event |Sex | age |
| ---- | ---- | ----|
| 3| 1 | 1|
| 4| 1 | 2|
| 5| 2 | 1|
| 6| 2 | 2|

Event is defined by Event UID in Event database #33 
Sex is defined as Male =1, Female =2
Age is defined as <5 =1, >5=2

Database structure: Converting previous two hash text messages into four hash database.

| Event | Male<5 | Male>5 | Female<5 | Female>5 |
| ---- | ---- | ---- | ---- | ---- |
| 3 | 1 | 0 | 0 | 0 |
| 4 | 0 | 1 | 0 | 0 |
| 5 | 0 | 0 | 1 | 0 |
| 6 | 0 | 0 | 0 | 1 |

Related background tickets:
* SMS to database #25 
* How events are stores: #33 
* Background on single case reporting: #44 
* Background on aggregated case reporting: #46 
* Report database #48 
* Get SMS format flag from CBS form definition #37 
* Mapping of phone to location #26

Constraints:
Original report is always kept as its own variable. 

**Confirmation:**
All example two hash text messages sent and recorded in 4 hash system database.

**Comment by karolikl** [comment]
@aninek, at the moment all single case reports and aggregated case reports are displayed in the same way, meaning you're not able to see the actual age (you only see over5/under5). 

My worry is that you, in fact, want to see the specific age supplied in the single case reports. Could you please provide some insights into this? 

At the moment, this is what is listed: 
![image](https://user-images.githubusercontent.com/5235776/32836663-e132f614-ca0a-11e7-81f1-bc55908c8136.png)

**Comment by aninek** [comment]
We have gone around in circles on this, but have landed on <5 and >5 being sufficient data for outbreak investigation/deciding on response. Limiting to <5 and >5 age groups also means single case reports will be less identifiable (e.g. perhaps only 1 13 year old boy living in the community, but many >5 years), which is good. So in conclusion: we only need under five or over five.
