### ISSUE TITLE
Change single case reporting age variable

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#460]
The age variable of the single case reporting should be changed from 'age in years' to 'age group' (<5years or >5 years). 

New format of single case report:

|Event | Sex of case | Age group|
| ---- | ---- | ----|
| 1| 2| 1 |

Interpretation of age group values:
1 = <=5 years 
2 = >5 years (from 6 and up)

For non-human health risks, it will be enough with the health risk id. If Age group value is something other than 1 or 2, report is invalid. 

The change in age format is requested to simplify data collection and ensure data minimisation (we don't need to know exact age to know whether a reported health risk should trigger an alert), and for anonymisation of data purposes. E.g. there may only be one 3 year old male child in within the geographical location of the report, but it is likely there are more than one under the age of 5, meaning, the single case report cannot be traced back to an individual.

**Comment by Velcrow81** [comment]
If either sex or age group is 0, the report will sende 0 on human count in the report, meaning 0 girls over/under 5 and 0 boys over/under 5

**Comment by Velcrow81** [comment]
Age group 1 means 5 or younger. 2 means 6 or older

**Comment by Velcrow81** [comment]
Also added support for single digit reports, meaning i.e. 0 or 5 are valid reports. Do you agree on this and the limitations described above @aninek ?

**Comment by Velcrow81** [comment]
That is correct. We should update the description to say that if you have 3 numbers, the numbers for sex or age group must be either 1 or 2. The reason for this is that if only one is zero, its more difficult to know what the intention of the sender was. Was it really a non human healthrisk or a human health risk?The code now allows for single digit reports for non-human health risks. Meaning i.e. 0 for zero reports and 5 for flood (if those were the right health risk Ids).  How does that sound @aninek ?

**Comment by aninek** [comment]
sounds perfect!
