### ISSUE TITLE
Frontend should fetch a subset of the Case Reports

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#463]
As it is now, the VolunteerReporting/Web.Angular page fetches all Case Reports from the database. This will cause scalabilityproblems in the future when the database grows.
A way to solve this is, as suggested by @karolikl, to let the backend deal with this so that only a maximum of X Case Reports will be fetched from the database.

The backend can deal with this by for example giving the fetch-method some input so that the DB can determine how many Case Reports we want to be showable on the case report list.

**Comment by woksin** [comment]
MVP? @karolikl @Velcrow81

**Comment by Velcrow81** [comment]
Definatly something we need. And case reports are going to be the most numerous entity in our system, so the best place to start :)
