### ISSUE TITLE
Update the case report model used in the view with a specialized read model that provides everything for the view

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#467]
New read model called CaseReportForListing

**Comment by woksin** [comment]
@Velcrow81 What will this read model be used for exactly? It may be what I'm looking for when optimizing the frontend, look #463.

**Comment by Velcrow81** [comment]
@woksin : This will be the ream model you are looking for. Otherwise I am doing it wrong :)

**Comment by woksin** [comment]
Great!

**Comment by Velcrow81** [comment]
@woksin : Created issue #469 were you could update view to use this new model :)
