### ISSUE TITLE
Update case report view to use the new specialized read model

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#469]
The read model does not contain details on failed or unknown case reports, just a status (according to the mockup). It is assumed that this information will be shown in other views were i.e. users can fix messages that failed parsing. Is this correct @karolikl and @alexanderhoset ?

**Comment by Velcrow81** [comment]
Related to Update the case report model used in the view with a specialized read model that provides everything for the view #467

**Comment by woksin** [comment]
I will take a look at this it today.

**Comment by woksin** [comment]
@Velcrow81 Close this? #472
