### ISSUE TITLE
Update staff user

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#471]
Add endpoint for updating staff users in UserController.cs.

Please also update the route of the UserController to to api/
staffuser instead of api/usermanagement/staffuser.

**Comment by woksin** [comment]
Dependent on #354, @karolikl ?

**Comment by karolikl** [comment]
Correct :)

**Comment by woksin** [comment]
Similar to #499

**Comment by karolikl** [comment]
@woksin, can this be closed?

**Comment by woksin** [comment]
@karolikl very soon, I'll implement the rest of the update functionality before monday
