### ISSUE TITLE
CaseReportForListing collection contains 99/100 reports

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#473]
It seems like not all of the reports are put into the CaseReportForListing collection.
Here are screenshots I took when I was debugging using the swagger Controller interface and using only the GetAllAsync methods in each respective collection: CaseReport-collection CaseReportFromUnknown..-collection, ...
![1](https://user-images.githubusercontent.com/13407188/36428945-8f52aedc-1651-11e8-898a-b707e1ab5a79.PNG)
![2](https://user-images.githubusercontent.com/13407188/36428948-8fa2e492-1651-11e8-9ffe-a8bfc0bfc4fd.PNG)
![3](https://user-images.githubusercontent.com/13407188/36428950-8fbf3eb2-1651-11e8-8daf-a23aa06ff0d8.PNG)
![4](https://user-images.githubusercontent.com/13407188/36428951-8fdbf9f8-1651-11e8-9ce3-6bcb852003bc.PNG)
![5](https://user-images.githubusercontent.com/13407188/36428952-9005993e-1651-11e8-9880-723ebd9640e1.PNG)
![6](https://user-images.githubusercontent.com/13407188/36428953-903b5da8-1651-11e8-9de0-efa958ff6716.PNG)

If you want to replicate this try putting a breakpoint infront of each collection's GetAllAsync-method.

**Comment by Velcrow81** [comment]
@einari : Do you have any experience with this? The new read model I created should hold all the reports, but one seems to be missing.

**Comment by karolikl** [comment]
I think I found the issue. We're getting a NullReferenceException for one of the messages added in the CaseReportForListingEventProcessor.cs: 

![image](https://user-images.githubusercontent.com/5235776/36501639-f6bc5716-1747-11e8-8333-b5828d4c5e8a.png)

**Comment by karolikl** [comment]
To provide more detail: healthRisk is null

**Comment by woksin** [comment]
Good job tracking it down.
Should healthRisk have been null in that case or not?

**Comment by Velcrow81** [comment]
Aaaaaaaaahhhhhh :) So the health risk test data is incomplete? I guess one of the reports have GUID.Empty and then it cannot find a health risk based on that. I think the problem is with TextMessageProcessor:
```
// Todo: Should we have a validation check if we actually get a health risk id
            var healthRiskId = _healthRisks.GetIdFromReadableId(parsingResult.Numbers[0]);
```
As you can see from the todo, this could have been stopped earlier :) There should be a check that if its GUID.Empty, then it should emit an invalid report with a new error message explaining this problem. Do you @karolikl want the pleasure of fixing it since you found it? I see you self assigned :)

**Comment by karolikl** [comment]
Hahaha, todos are the best. I'm on it :)

**Comment by woksin** [comment]
This bug made me realize that these kinds of bugs can be quite devestating in the CBS system.
Imagine having a report that is not processed because of some field not being provided at construction, because of whatever reason, it can be very devastating.

The chance that this might happen is not that unlikely in my opinion because of the event sourcing architecture. We cannot, in a sense, have complete control of what's going in the system. My opinion is that we should make it so the system is "idiot-proof". Doing checks on fields, and perhaps make dummy, replacer, values instead or something. I have no concrete suggestion at the moment.

**Comment by Ulriksen** [comment]
make it impossible to create illegal states. Private setters + constructors. Serialization, if needed,  might be a bit tougher.

**Comment by einari** [comment]
That is a very good point. This is possible to do right now as the ISerializer in Dolittle (a small wrapper around Newtonsoft.JSON) actually supports a convention that deserializes properties directly into constructor parameters with the same name - see [here](https://github.com/dolittle/DotNET.Fundamentals/blob/master/Source/Serialization.Json/Serializer.cs) (line 169 right now)

We're also looking at formalizing this even further - see [here](https://github.com/dolittle/DotNET.Fundamentals/issues/2)

**Comment by Velcrow81** [comment]
@woksin: You are correct in that errors in events will cause problems :) 
An event should not have any nullable fields (if something is optional it should probably be a separate event) and they are protected behind specialized constructors. What was missing here was input validation that should stopped the default value of the GUID. Input validation and business input validation are supposed to be applied before the aggregate root allows an event to be created. Events are per definition immutable, but we can fix a faulty event with a correcting event later.
