### ISSUE TITLE
Move all deployment files to Deploy/templates folder

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#485]
We're using Helm to deploy the solution, and have created a Helm chart in the Deploy folder (on root). 

If all the infrastructure deployment files are moved to the Deploy/templates folder, they will be part of the Helm chart and Helm can be used to deploy/update the entire CBS solution.

**Comment by einari** [comment]
Since every Bounded context should be isolated and be deployable on their own, I suggest we have charts per BC - High cohesion. 
We could however have a common one for deploying it all for typically local deployment.

**Comment by karolikl** [comment]
I agree on separating them on bounded contexts, but all "global" infrastructure should probably live in one chart?
