### ISSUE TITLE
Add URL config for navigation

### ISSUE THREAD

**Issue by Virrum** [IFRCGo/cbs#514]
### Description
At deployment stage, we need to know what environment we are in, and thus set the correct url for the different applications that is using the navigation bar as UI Glue

### Environment
* All

**Comment by jakhog** [comment]
Is this still relevant after #615 ?

**Comment by Virrum** [comment]
Yes, I think so. I'm to fix some styling on the navigation now, so I'll take a look at it

**Comment by Virrum** [comment]
No, seems like the current setting with relative links will work in production, so we don't need this anymore @jakhog

**Comment by jakhog** [comment]
Then I guess we can close this down 😄
