### ISSUE TITLE
Add navigation bar to Volunteer Reporting

### ISSUE THREAD

**Issue by Virrum** [IFRCGo/cbs#517]
When the nav bar is done in Admin in #515 , this can be replicated in User Managment

**Comment by eprom** [comment]
@Virrum or @alexanderhoset,  is this issue completed? #515 and #550 are already closed.

**Comment by karolikl** [comment]
No, this is not completed yet. It has been added to Admin, but not to Volunteer Reporting (which is this issue). If I've understood the issue correctly, we can replicate what was done in #550 in Volunteer Reporting to complete this.
