### ISSUE TITLE
Rename "Project" to "National Society Data Repository"

### ISSUE THREAD

**Issue by dageirikboe** [IFRCGo/cbs#528]
Project should be renamed to National Society Data Repository (NSDR)
One NSDR will have one Data Owner.
The term Project should only be used in the reporting bounded context to describe a filter on which reports are shown in the reports.

**Comment by eprom** [comment]
The term Project and Data Repository need clear definitions. This should be incorporated in the blueprint.

**Comment by alexanderhoset** [comment]
this issue is obsolete
