### ISSUE TITLE
All backends failing with due to exception in doLittle.Assemblies.ICanProvideAssemblies

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#532]
All backends running in our dev cluster are currently failing with the following exception: 

Application startup exception: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = CommittedEventStreamCoordinator (ReflectionActivator), Services
= [doLittle.Runtime.Events.Coordination.ICommittedEventStreamCoordinator], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = EventProcessors (ReflectionActivator), Services = [doLittle.Runtime.Events.Processing.IEventProcessors], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ApplicationResources (ReflectionActivator), Services = [doLittle.Runtime.Applications.ApplicationResources, doLittle.Runtime.Applications.IApplicationResources], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred
during the activation of a particular registration. See the inner exception for details. Registration: Activator = ApplicationResourceTypes (ReflectionActivator), Services = [doLittle.Runtime.Applications.ApplicationResourceTypes, doLittle.Runtime.Applications.IApplicationResourceTypes], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = InstancesOf`1 (ReflectionActivator), Services = [doLittle.Types.IInstancesOf`1[[doLittle.Runtime.Applications.IApplicationResourceType, doLittle.Runtime.Applications, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TypeFinder (ReflectionActivator), Services = [doLittle.Types.TypeFinder, doLittle.Types.ITypeFinder], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Assemblies (ReflectionActivator), Services = [doLittle.Assemblies.Assemblies, doLittle.Assemblies.IAssemblies], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AssemblyProvider (ReflectionActivator), Services = [doLittle.Assemblies.AssemblyProvider, doLittle.Assemblies.IAssemblyProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(System.Collections.Generic.IEnumerable`1[doLittle.Assemblies.ICanProvideAssemblies], doLittle.Assemblies.IAssemblyFilters, doLittle.Assemblies.IAssemblyUtility, doLittle.Assemblies.IAssemblySpecifiers)' on type 'AssemblyProvider'. ---> Could not load file or assembly 'Web.PrecompiledViews, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by einari** [comment]
Interesting.
I notice that it is looking for a `Web.PrecompiledViews`assembly. Are we doing something on build for precompiling razor pages?  That sounds wrong if so - don't think we're supposed to be doing MVC + Razor Views.

Tips on reproduction locally?

**Comment by karolikl** [comment]
You should be able to reproduce locally if you pull and run one of the following images: 

karolikl/cbs-vr-backend:1488
karolikl/cbs-admin-backend:1489
karolikl/cbs-usermgmt-backend:1490

**Comment by einari** [comment]
My hopeful fix did not fix it.
I think I have a way of reproducing it locally now - was going to deploy SmsEagle endpoint and got the same error.

**Comment by karolikl** [comment]
Changes are currently not being deployed to the dev environment automatically (as we're in the process of moving away from vsts). So the changes haven't been deployed yet. I can trigger a deployment now to see if it helps.

**Comment by karolikl** [comment]
Update: Will have to update the pods later on today. Will post a comment here when done.

**Comment by karolikl** [comment]
@einari, we pushed a new version last night, but the backends are still failing with the same errors.

**Comment by einari** [comment]
Yup.  Was expecting that to fail. Didn't have time yesterday to fix it - hoping later today / tonight. I have the fix in my head - just needs to be done and tested.

**Comment by einari** [comment]
Fascinating... Different error - in fact, no error - no nothing. It just doesn't start properly. Investigating.

**Comment by einari** [comment]
Located and completely makes sense.. 
My bad; with the new inter bounded context communication system, it tries to hook up for a topic that it is expecting from an environment variable passed into the container. 

Well.. I have that - but since it is not something that is set as a requirement, it is not included in the deployment. Weird enough though, it works in development but inside a container it just dies without any message.  Found, reproduced, fixed..   PR coming.

**Comment by Velcrow81** [comment]
We look forward to the PR 😊

**Comment by karolikl** [comment]
Deployed, and it works!! 🥇
