### ISSUE TITLE
doLittle.Events.Processing package cannot be found

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#535]
Builds failing because of missing package: doLittle.Events.Processing. 

The package used to be on MyGet: https://www.myget.org/gallery/dolittle 
Looking at a cached view of the feed, the doLittle.Events.Processing package used to exist there: 
https://webcache.googleusercontent.com/search?q=cache:BSXzQ-vnuX4J:https://www.myget.org/gallery/dolittle+&cd=2&hl=en&ct=clnk&gl=no 

But in the current feed, it's gone. I see most of the dolittle packages on MyGet were updated 1 day ago, so I suspect this is when it disappeared...

Has the package been moved?

**Comment by einari** [comment]
This is now fixed - on NuGet. It was a slip - all packages used by this project had been moved to NuGet, except this one..  Sorry for any inconvenience!
