### ISSUE TITLE
All Travis and AppVeyor builds failing with dolittle warnings and errors

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#539]
All Travis and AppVeyor builds are currently failing due to dolittle package dependencies and references. Build log is too long to include in this issue, please see these: 

- AppVeyor: https://ci.appveyor.com/project/karolikl/cbs-g81xy/build/1.1.0-59 
- TravisCI: https://travis-ci.org/IFRCGo/cbs/builds/352001537?utm_source=github_status&utm_medium=notification 

![image](https://user-images.githubusercontent.com/5235776/37256988-2c82fd4a-2563-11e8-912e-6a18a2072b95.png)

**Comment by einari** [comment]
The fix that I've put in won't remove the warnings - the warnings are OK, it will work @ runtime. 
There are some components put in that rely on a newer build, but the APIs haven't broken and they are able to be bound at runtime. 

The warnings will go away when we have all versions aligned in Dolittle - which we're aiming for by the end of next week with a major 2.0.0 release.
