### ISSUE TITLE
Backend in dev environment is unavailable

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#544]
http://dev.cbsrc.org/volunteerreportingbackend/api/casereports/getlimitlast?limit=10 responds with 503 (Service Temporarily Unavailable)

**Comment by Velcrow81** [comment]
@karolikl : Is there a problem with nginx?

**Comment by woksin** [comment]
@Velcrow81 I implemented that part 😰 Do you get an exception or something when querying the MongoDB?

**Comment by alexanderhoset** [comment]
Shot in the dark...
forgot to update image tags in the values.yaml ref #531 during deploy?

**Comment by karolikl** [comment]
Sorry for the late reply. The reason all the backends are failing is because of this: #532. As it affects all backends, it is most probably an infrastructure issue.

**Comment by karolikl** [comment]
Backends are up and running! 🥇
