### ISSUE TITLE
Show phone number for unknown data collectors

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#595]
If a case report is received from an unknown number, we need to display the phone number (in the data collector column). 

![image](https://user-images.githubusercontent.com/5235776/38332052-4dae1310-3855-11e8-9d92-a0a279a218a0.png)

**Comment by woksin** [comment]
I can fix this 👍

**Comment by woksin** [comment]
Should work because of #598 .
Can be closed when we can confirm this is working in the production environment.
