### ISSUE TITLE
Add Build Shields to ReadMe

### ISSUE THREAD

**Issue by einari** [IFRCGo/cbs#6]
Have a Table on the ReadMe.MD file on the root that holds all the build shields per project. 
There will be a build per bounded context and we need to reflect the status here.

Also, all build details should be available on the Documentation Site - meaning the index.md should hold this as well in the Documentation folder

**Comment by karolikl** [comment]
@einari, I have added build shields to the root readme.md (https://github.com/IFRCGo/cbs) and to each individual project's readme in the Source folder (https://github.com/IFRCGo/cbs/tree/master/Source/Example). Do you also want one in the Documentation folder? If so, where?

**Comment by einari** [comment]
Great. The documentation folder can wait. Depends a bit on what we do. If we want to generate a site with the documentation on, it would be nice to have it on the index page of that. I'll bring the discussion up on Slack for that topic.
