### ISSUE TITLE
Not all incoming SMS reports are shown in Volunteer Reporting

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#600]
We have an issue with only some incoming SMS' being shown in dev.cbsrc.org/reporting/ 

It seems mesasges containing text only are registered correctly, while those containing numbers are not (need to verify this).

**Comment by karolikl** [comment]
We've tested this quite extensively in the VolunteerReporting bounded context. Using the /api/textmessages endpoint in Infrastructure.TextMessaging, we see that all test messages are parsed as expected (also those that fail when sending them in as an actual SMS). 

Example of message that fail via SMS, but works through the endpoint: 
```
{
    "Id": "c00654a2-a2e7-41fd-9454-c52edfa0ffc4",
    "Sent": "2018-04-09T11:30:40.2923004+02:00",
    "OriginNumber": "11111134",
    "Message": "12334",
    "Keyword": "",
    "ReceivedAtGatewayNumber": "0123456789",
    "Longitude": 13.578119545047228,
    "Latitude": -32.979689404824612
  }

```

**Comment by woksin** [comment]
We figured that this was probably solved with the stuff @einari and @Velcrow81 pushed?

**Comment by Velcrow81** [comment]
Correct. That is our hope 😊

**Comment by karolikl** [comment]
Fixed.
