### ISSUE TITLE
Remove Reporting navbar

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#630]
Remove reporting navbar: 
![image](https://user-images.githubusercontent.com/5235776/38671174-ffd3418c-3e4a-11e8-8f92-057476aadb20.png)

Also, make the list of reports the default view when going to dev.cbsrc.org/reporting

**Comment by alexanderhoset** [comment]
fixed by #638 ? Did that include the redirect to the list @karolikl ? 

Not sure if we need 
`const routes: Routes = [
    {
        path: '',
        redirectTo: 'case-report/list',
        pathMatch: 'full'
    }
];`

or if as-is is fine because / is mapped  to list internally
`const routes: Routes = [
    {
        path: '',
        redirectTo: 'case-report',
        pathMatch: 'full'
    }
];`  
`const routes: Routes = [
  {
    path: 'case-report',
    children: [
      {
        path: '',
        redirectTo: 'list',
        pathMatch: 'full'
      },
      {
        path: 'list',
        component: CaseReportListComponent
      }
    ]
  }
];`

**Comment by karolikl** [comment]
Thanks, this is fixed by #638 :)
