### ISSUE TITLE
Register new Volunteer (App Form)

### ISSUE THREAD

**Issue by aninek** [IFRCGo/cbs#64]
**Purpose:** 
We need a user interface for registering new Volunteers to CBS that works offline on a mobile device. Related to #13 - User database.

**Conversation:**
Variables for collection (sub-set of database #13 ) in App form:
* FirstName
* LastName
* Age
* Sex (Options: Male, Female)
* National Society (Options: pull from FDRS)
* Preferred language (Options: English, French, but flexible for the addition of more languages)
* GPS location: Important for Volunteer, but not necessary higher level Roles because we need Village name that may/may not exist in official Administrative boundaries.
* Mobile phone number: Validation rules for Mobile phone number should be applied - and localized.
* Email address: Typical validation rules

Additional data collection from form creation:
* Assigned project: This information should be stored within the form hierarchy (e.g. Project 1 -> New Volunteer registration form).  Projects may have multiples forms. 
* Date of activation (#65): System recorded
* Last updated: System recorded. Revision history for tracking changes in User data, especially GPS.

**Comment by cathinkaw** [comment]
Comment from discussion with Inge in Admin:

I know that a frequent use-case is Data Collectors with multiple numbers. I think User Mgmt must discuss with Anine or other RC domain expert to determine, but we in Volunteer Reporting are happy with a primary number and possible secondary numbers. Maybe #team_alerts needs to also take this into account (We are considering the option for manual SMS sending to target only primary phone or all phones for a given data collector)

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/2jkmQSBm
