### ISSUE TITLE
Add textbox for area code when registering a data collector

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#642]
At the moment, all phone numbers need to be registered in the format +4799999999 (area code + number without spaces). 

We need to add a separate textbox (or dropdown) for the area code to make registration easier. 

Remember, you must still be able to add multiple phone numbers for a data collector.

**Comment by woksin** [comment]
Same as #648 (?)

**Comment by woksin** [comment]
This should be solved as described in #648
