### ISSUE TITLE
Enforce validation on required fields of data collector registration form 

### ISSUE THREAD

**Issue by eprom** [IFRCGo/cbs#646]
### Data Collector Registation From Fields
* Full name (Required)
* Display name (Required)
* Year of Birth (Required)
* Sex (Required)
* Location (Required)
* Address (optional)
* Phone numbers (Required) (comma separated, the same country code is populated for list of phone numbers)

**Comment by karolikl** [comment]
@eprom, do we need National Society on a data collector as they are always registered in the context of a national society?

**Comment by eprom** [comment]
@karolikl Good point. Let's remove it. We can get it from the phone number or from data verifier during data collector registration.

**Comment by alexanderhoset** [comment]
I guess I can fix this one! Do you have a accept patten for them @eprom,  just required?

**Comment by eprom** [comment]
@alexanderhoset updated required and optional fields.
