### ISSUE TITLE
Rename age properties in reports to match domain language

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#651]
From 
       NumberOfFemalesAgedOver4
       NumberOfFemalesAges0To4
       NumberOfMalesAgedOver4
       NumberOfMalesAges0To4

To
     NumberOfFemalesAged5AndOlder
     NumberOfFemalesUnder5 
     NumberOfMalesAged5AndOlder
     NumberOfMalesUnder5

**Comment by eprom** [comment]
@Velcrow81 seems you have questions for @einari in your #653 PR. Seems some clean up is needed?

**Comment by esp0** [comment]
Searching the code, this seems to be solved.
