### ISSUE TITLE
Populate Message property when SMS is correctly parsed

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#656]
Today, the Message property is null when an SMS is correctly parsed, while it is populated with the SMS content when it is incorrectly parsed. 

We need Message to be populated for correctly parsed case reports as well.

**Comment by woksin** [comment]
@karolikl This field has been correctly populated in the past, does this now happen every time we send a correctly formated sms?

**Comment by karolikl** [comment]
Yes, it happens every time we send a correctly formatted SMS, Message is always null.

**Comment by woksin** [comment]
My gut feeling tells me that #657 and #656 are related. I can take a look at this tomorow, unless anyone else wants to

**Comment by woksin** [comment]
Should be fixed with #662,
