### ISSUE TITLE
Show Lat/Long in case report list when data collector is known

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#659]
Even when the case report is invalid, it might be useful to show the position of the datacollector

**Comment by woksin** [comment]
Any opinions on this, @aninek

**Comment by aninek** [comment]
@woksin that would be the dream, but given that the only way to get gps is through registration of data collectors I don´t see how it can be possible to show position on unknown data collectors. If data collector is known but SMS format is invalid the GPS should be shown.
