### ISSUE TITLE
Change datatype of timestamp in export to excel

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#676]
Change the datatype to datatime / datetimeoffset

**Comment by jakhog** [comment]
For .xslx files I agree, they have a datatype (I just need to figure out the string format to feed the tool).

But for .csv files, there are no datatypes. So the only thing we can aim for is to write the timestamp in a format that most tools support when importing it. I guess a standard ISOxxx format should suffice.

**Comment by eprom** [comment]
@jakhog what is the status of this issue?
