### ISSUE TITLE
Error messages for SMS reporting

### ISSUE THREAD

**Issue by RFMoore** [IFRCGo/cbs#68]
**Purpose:** 
CBS follows a strict reporting format.  If a user reports an SMS that does not follow the strict reporting format, s/he receive an error message and ask to resend, however the system records the original message.

**Conversation:**
Single reporting: SMS reports must come in format:  [Number] # [Number] # [Number]

|Number in SMS format | Rule | Message |
| ---- | ---- | ---- |
| First number| Must be Event UID from affiliated project (CBD project #35 ) | Please respond with appropriate event code: [Event UID] [Event name] ..." (repeating for number of event codes) |
| Second number | Must be 1-3. | Please respond with appropriate sex:  1 Male 2 Female |
| Third number | Must be 1 or 2. | Please response with appropriate age: 1 under 5 years of age 2 over 5 years |

Rule logic governing the first reporting structure must not throw error messages for the second reporting structure (identifiable via four hash number system). 

Aggregated reporting:  SMS reports must come in format: [Number] # [Number] # [Number] # [Number] # [Number]

|Number in SMS format | Rule | Message |
| ---- | ---- | ---- |
| First number | Must be Event UID from affiliated project (CBD project #35 ) | Please respond with appropriate event code: [Event UID] [Event name] ..." (repeating for number of event codes) |
| Second number | Must be numeric greater than or equal to 0 |
| Third number | Must be greater than or equal to 0 |
| Fourth number| Must be numeric greater than or equal to 0 |
| Fifth number| Must be greater than or equal to 0 |

When a user submits a report with an error message, this triggers a response SMS notifying of error and how to fix (project: Volunteer reporting).

Related projects: 
Mapping of how "single reporting" text messages fit into the "aggregated reporting" database structure is available #45 .

**Confirmation:**
Submit text message that triggers each error message and confirm appropriate user message.

**Comment by alexanderhoset** [comment]
moved to https://trello.com/c/xD69Q6M9

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/xD69Q6M9
