### ISSUE TITLE
Aggregate case reports not received

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#692]
During our field test this weekend, several aggregate case reports were submitted via SMS, but they are nowhere to be found in the dev environment. 

Examples: 
- 7#6#6#4#8 (sent from +959402934665)
- 7#3#6#9#10 (sent from +959402934665)
- 7#6#3#3#6 (sent from +959253930455)
- 7#3#5#9#6 (sent from +959253930455)

All single case reports from the same numbers are received and parsed correctly. 

I have only checked whether the reports are returned by the reporting backend APIs, and they are not. We need to verify whether the reports are in MongoDB at all or whether they were lost before they reached VolunteerReporting.

**Comment by woksin** [comment]
The weird thing is that @aninek tested aggregate reports the day before and it worked.

**Comment by woksin** [comment]
Me and @einari tested this today by sending text messages through the API to the SMSEagle, all of them came through to dev.cbsrc.org

**Comment by aninek** [comment]
@karolikl were single case reports from those numbers received also after the missing aggregate reports? could it be linked to having run out of credit on the SMS eagle sim? and does the SIM need credit to receive and transmit SMS reports in general? @eprom

**Comment by karolikl** [comment]
The single case reports were received, yes. The data collectors received a thank you message for all the "missing" reports, so I don't believe credits to be the issue. As discussed in the core team sync, SMS Eagle sends the reports over the internet, so this should not be affected by credits either.

**Comment by eprom** [comment]
I agree with @karolikl. We had a post-paid SIM with unlimited SMS and 1GB data (which is quite enough), but @aninek yes receiving and sending acknowledgement messages needs enough credit on the SIM.

**Comment by karolikl** [comment]
Closing as we cannot reproduce.
