### ISSUE TITLE
HealthRiskModified

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#694]
public Guid Id { get; set; }
        public string Name { get; set; }
        public int ReadableId { get; set; }
        public string CaseDefinition { get; set; }

        public string Note { get; set; } //TODO: Separate Command
        public string CommunityCase { get; set; }//TODO: Separate Command
        public string KeyMessage { get; set; }

**Comment by woksin** [comment]
Due to time constraints, one can change any field of a health risk. This is probably not something that we want in the long run

**Comment by eprom** [comment]
Closing. Summarised events are here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
