### ISSUE TITLE
add location information to data collector registration

### ISSUE THREAD

**Issue by aninek** [IFRCGo/cbs#695]
Linked to #491 

Add input fields:
- Region

- District 

- Village 

to data collector registration

**Comment by woksin** [comment]
@aninek will this information be required or optional? Do you want this by Tuesday?

**Comment by aninek** [comment]
@woksin region and district required, village optional. all should optional to export from volunteer reporting view

**Comment by aninek** [comment]
and yes, if we could have it by Tuesday that would be most helpful! :)
