### ISSUE TITLE
Data Collectors does not show up in list

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#697]
Figure out why data collectors are not listed in http://dev.cbsrc.org/users/

Response status = 204 No Content

It works locally

**Comment by einari** [comment]
It seems to be working in the production environment as well

**Comment by woksin** [comment]
I suspect that there is some corrupted data in dev.
Either way, when we use Queries in the frontend #717 we get a detailed QueryResult that should contain the information we need to figure out what's wrong. 

I'm working on it
