### ISSUE TITLE
Change date formatting in export of volunteer reporting

### ISSUE THREAD

**Issue by RebeccaBushby** [IFRCGo/cbs#736]
When the timestamp (date) is exported to excel it takes the form "year, month (in letters), date". However, it would be useful if it was exported as dd.mm.yy (numerically) to allow for manual data analysis.

**Comment by RebeccaBushby** [comment]
This has now become a high priority! @jakhog @eprom, could one of you please look at this asap?

**Comment by esp0** [comment]
I can take a look at this tomorrow during the code evening.

**Comment by esp0** [comment]
Workaround:
1.	The regional settings for the computer need to be set to English
2.	Insert a new column into the excel sheet by right-clicking on column B and choosing “Insert”
3.	Select cell B2 and put this formula into the formula bar:
`=DATEVALUE(VALUE(RIGHT(A2,2))&"-"&MID(A2,6,FIND(" ",A2,6)-6)&"-"&LEFT(A2,4))`
4.	Right click on column B, choose "Format Cells", and pick date.
5.	Double click on the lower right corner of the cell to copy the formula to all the rows

**Comment by guddukaur** [comment]
THANK YOU ESPEN! 

It works and saved a bunch of time! (Get it? I made a time/date joke).

**Comment by esp0** [comment]
I think this is fixed by PR #1000 , but I have not confirmed it. To confirm, export a list of case-reports to excel and then create a new column with a date formula, like this:
`=DATE(YEAR(A2) + 5, MONTH(A2), DAY(A2)) `
This should display a date that is 5 years after the value in A2.

**Comment by cathinkaw** [comment]
@woksin kan you maybe have a look at this? See Espen's comment above :)
