### ISSUE TITLE
Hide Case Report from listing

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#737]
Create a "hide" button that effectively can remove a case report for listing so that it does not appear in the front end view.

Unknowns: 
- Is this needed with the training feature for data collectors?
- Will be reports be hidden from Analytics?
- We need proper user stories for this.

**Comment by eprom** [comment]
@woksin is it for deleting a case report both in the backend and front-end? Why you chose to use the word "hard-to-delete" not just "Delete"?
