### ISSUE TITLE
Operations dashboard

### ISSUE THREAD

**Issue by RFMoore** [IFRCGo/cbs#75]
**Purpose:**
As a health actor, I want to have a quick overview of reported events within my geographic scope.

**Conversation:**
![fullsizerender](https://user-images.githubusercontent.com/8931230/30984279-2bc8981c-a48d-11e7-83c7-1fe8adee6970.jpg) @RFMoore

**Confirmation:**
Approved dashboard

**Comment by alexanderhoset** [comment]
Same issue as #163
