### ISSUE TITLE
Enable training mode for data collectors

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#755]
Add two new events:

DataCollectorBeganTraining  
Event properties:
Guid DataCollectorId

DataCollectorCompletedTraining
Event properties:
Guid DataCollectorId 

DataCollector read model new properties:
bool InTraining => Indicates if data collector is in training or not. DataCollectorBegunTraining => true, DataCollectorCompletedTraining => false
DateTimeOffset LastTrainingBegunAt => timestamp from last time the data collector was put in training 

Add also commands that can be sent from UI that will result in events

For more background see #711

**Comment by Velcrow81** [comment]
Do you mean last training begun at? That is important for a policy that will automatically end the training for any datacollectors that have been in training for more than 48 hours. Or do you mean something else?

**Comment by cathinkaw** [comment]
Yes, but there is another issue on that, where I feel it's more logical to add a time stamp. 

Also based on some of our discussions with Anine and Roxanne today we are a bit uncertain if it is correct to change the staut automatically after 48h,. So we to discuss that more with them when fixing the other issue.

**Comment by cathinkaw** [comment]
Remaining tasks:

- [ ] Manually edit training status
- [ ]  Display value if the data collector list (if this is a need)

**Comment by gardnk** [comment]
Fixed in #1180 

Training mode can now be switched manually with a button in actions part of the data collector list
