### ISSUE TITLE
DataCollectors that have been in training for 48 hours should end their training automatically

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#759]
From #711:
"There are a number of ways we can do it. I would suggest the easiest way is to use one of the scheduling libraries to schedule a recurring task that periodically checks the "time in training" and issues a CompleteTraining command to DataCollectors who have been in training >= 48hrs and satisfy whatever other criteria (e.g. have sent X training messages successfully)."

In the future this should be a policy, but timers are not supported on policies yet. 

Depends on #755

**Comment by cathinkaw** [comment]
From #755: "DateTimeOffset LastTrainingBegunAt => timestamp from last time the data collector was put in training"

See also discussion about whether this functionality actually should be implemented or not.

**Comment by Velcrow81** [comment]
@aninek : Do you want the switch from training to be done manually? What og this is forgotten? Then there could be a greater risk for missing real case reports since they Are labeled wrong? Is it the timeframe that is problematic? This could be changable or i.e based on 48 hours since the last training case report was submitted? What is your thoughts?

**Comment by aninek** [comment]
I think default should be data colectors are automatically in training mode from registration for 48h. Then automatically in 'real'/'live' mode, with option to override both modes manually.

**Comment by gardnk** [comment]
After discussions this has been removed as a requirement. Data collectors will be switched off training mode manually.
