### ISSUE TITLE
Only emit training case reports when a data collector in in training

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#760]
Update DataCollector read model to update according to DataCollectorBegunTraining  and DataCollectorCompletedTraining.
Depends on #755 

Add new event:
TrainingCaseReportRecieved, same properties as case report recieved

Keep all existing logic that deals with invalid reports and unknown data collector, but emit TrainingCaseReportRecieved instead of CaseReportRecieved if data collector is InTraining. Suggest new read models that only show training reports. Training reports should not show up in existing read model for cease reports. Use same aggregate as for casereports.

See #711 for more background

**Comment by gardnk** [comment]
Fixed in #1180
