### ISSUE TITLE
Have a second look at the Travis build setup

### ISSUE THREAD

**Issue by jakhog** [IFRCGo/cbs#770]
Currently Travis seems to build only the Admin project. IMHO, if we want to keep it, we should make it build all the projects, and make it easy to configure so that it can build new projects once they are created.

But, since we also have building in AppVeyor and Docker Cloud, maybe we don't need this as well? I'm not entirely sure...

**Comment by Velcrow81** [comment]
We should consider azure Devops pipelines, since that is for open source project and we have more experience with this tech in the core team

**Comment by karolikl** [comment]
I agree! The reason we didn't go for that in the first place was the lack of yaml support and that the build logs were not public. We now have support for both these things.

**Comment by Velcrow81** [comment]
I smell new issues for the codeathon :)

**Comment by jakhog** [comment]
I like the sound of that 👍

**Comment by jakhog** [comment]
It's gone now 😄
