### ISSUE TITLE
Status of incoming message if data collector is unknown but message is correctly parsed should not be 'success' but 'unknown user' in yellow colour.

### ISSUE THREAD

**Issue by aninek** [IFRCGo/cbs#773]

**Comment by ssokurenko** [comment]
Implemented: https://github.com/IFRCGo/cbs/pull/831

**Comment by ssokurenko** [comment]
<img width="1413" alt="screenshot 2018-09-30 at 18 34 29" src="https://user-images.githubusercontent.com/1279563/46259972-ae40c980-c4e0-11e8-82d8-ba4c30fff8ad.png">
<img width="1435" alt="screenshot 2018-09-30 at 18 34 59" src="https://user-images.githubusercontent.com/1279563/46259976-b13bba00-c4e0-11e8-9487-48123329a769.png">
<img width="1440" alt="screenshot 2018-09-30 at 18 35 51" src="https://user-images.githubusercontent.com/1279563/46259977-b4cf4100-c4e0-11e8-871f-df435940408d.png">
