### ISSUE TITLE
Events from Admin Bounded Context

### ISSUE THREAD

**Issue by eprom** [IFRCGo/cbs#78]
Purpose: we want to capture the events generated from admin bounded context.

Event structure

|Bounded Context ID|Bounded Context Type|Event ID| Event Type| Data|Event Consumed|
|---|---|---|---|---|---|
|101|Admin|1|ProjectCreated|Data|
|101|Admin|2|ProjectInfoAdded|Data|
|101|Admin|3|ProjectInfoChanged|Data|
|101|Admin|4|ProjectRemoved|Data|
|101|Admin|5|ProjectEventThresholdAdded|Data|
|101|Admin|6|ProjectEventThresholdChanged|Data|

**Comment by karolikl** [comment]
I have created card for all these events in our Event overview project: https://github.com/IFRCGo/cbs/projects/10
