### ISSUE TITLE
Change sorting from client-side to server-side on Report-page

### ISSUE THREAD

**Issue by esp0** [IFRCGo/cbs#817]
### Description
The current Volunteer Reporting list currently sorts on the client-side which is not a good solution when we do server-side paging.

The server-side code is ready to handle this by using the `SortField `and `SortAscending ` paramters to the `AllCaseReportsForListing`-query. 

Example query:
```
{
	"parameters":
	{
		"pageSize": 50,
		"pageNumber": 2,
		"sortField": "DataCollectorDisplayName",
		"sortAscending": false
	},
	"nameOfQuery": "allCaseReportsForListing",
	"generatedFrom": "Read.CaseReportsForListing.Queries.AllCaseReportsForListing"
}
```

**Comment by esp0** [comment]
Can you take a look @ssokurenko?

**Comment by ssokurenko** [comment]
Implemented https://github.com/IFRCGo/cbs/pull/829

**Comment by ssokurenko** [comment]
[](url)
<img width="1393" alt="screenshot 2018-09-29 at 20 49 56" src="https://user-images.githubusercontent.com/1279563/46249492-3f089e00-c42a-11e8-8793-9d7d42009bbd.png">
