### ISSUE TITLE
Error when exporting Volunteer Report to excel

### ISSUE THREAD

**Issue by esp0** [IFRCGo/cbs#824]
### Description
When exporting the report to excel the user receives an error-message:
![image](https://user-images.githubusercontent.com/102811/46246984-64cf7c00-c405-11e8-9b2a-3931ae51c176.png)

When clicking "Yes" you will get the data, but we dont know if it is correct.

**Comment by jakhog** [comment]
Can you upload one of those .xlsx files here @esp0 ? I expect we are not properly escaping some characters in the XML. But it's easier to see that if you could provide us with an example.

**Comment by esp0** [comment]
Here is an example created from dummy-data. (Dummy data-generation can be found [on slack](https://cbsv2.slack.com/archives/C7AV19XQC/p1538139104000100))
[casereports-2018-september-29.xlsx](https://github.com/IFRCGo/cbs/files/2436497/casereports-2018-september-29.xlsx)

**Comment by karolikl** [comment]
@esp0, this was fixed with the new implementation of export, correct?

**Comment by esp0** [comment]
> @esp0, this was fixed with the new implementation of export, correct?

Yes. I have added a "Fixes" text to that PR (now), but the PR is not closed, so we can not close this issue yet.
