### ISSUE TITLE
Redesign (to be turned into real issues) 

### ISSUE THREAD

**Issue by hodoea** [IFRCGo/cbs#842]
We are moving from Balsamiq to UXPin.

Follow this link for how the work of sketches is in progress: 
https://preview.uxpin.com/19a223e47b1f89a1ddf508490f8d0a8693166969#/pages/94929752

There is a sitemap to the left, use this to navigate between the sketches..
Please use the comment mode to leave your thoughts and such :)

**Comment by gardnk** [comment]
Closing this now as I have seen many sketches in UXPin
