### ISSUE TITLE
Epicurve by week frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#845]
Please see [analytics overall documentation](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/846.

Here we display a weekly `epicurve` (the epidemiological term for a time
series graph showing the number of reported cases on the y-axis and time
on the x-axis).

Important to note:

-   We display `year-isoweek` on the x-axis
-   Weeks with zero cases must be displayed

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/1532091/48142218-a678ff80-e2ac-11e8-8832-f5b1babe904a.png)

There is fake json data available at `cbs/Source/Analytics/Web.React/src/assets/data/epicurve_by_week.json`.

We have also implemented a back-end query to provide data for this, but it does not work. 

We also tried to implement a simple D3 graph as a skeleton example for linking the back and front end (`cbs/Source/Analytics/Web.React/src/components/Epicurve.js`) but this has not been completed as we couldn't get the back-end query to work.

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This fake json data file has 4 'levels':

- all (i.e. all the data -- national level)
- district
- region
- village

The 'geographical value' is stored in 'geo'. i.e. if `level=district`, then maybe `geo=Western Norway`. If `level=village` then maybe `geo=Oslo`.

`Sex` is:

- All
- Male
- Female

`Age` is:

- All
- Age <5
- Age 5+

`pop` contains the population if it exists. Otherwise it is -9.

**Comment by raubreywhite** [comment]
Please note that in principle, this will be superseded by: https://github.com/IFRCGo/cbs/issues/922

**Comment by karolikl** [comment]
A static version of this chart has been generated in the Web Template using Highcharts, see `Documentation/Projects/Analytics/Web%20Mockup/epicurvebyweek.html`

The Highchart has also been moved to the React frontend, see `/Source/Analytics/Web/src/components/Epicurvebyweek.js`
But this is still created using static data (in the .js file). 

**Remaining work:**
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by karolikl** [comment]
Querying backend for data is done. 

Remaining work:
- Generate chart based on user input, as mentioned by Richard above (#922)

**Comment by raubreywhite** [comment]
Done!
