### ISSUE TITLE
Epicurve by week backend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#846]
Please see [analytics overall documentation](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the backend for https://github.com/IFRCGo/cbs/issues/845.

This is the current attempt: https://github.com/IFRCGo/cbs/tree/master/Source/Analytics/Web/CaseReports but it does not work.

Here we display a weekly `epicurve` (the epidemiological term for a time
series graph showing the number of reported cases on the y-axis and time
on the x-axis).

Important to note:

-   We display `year-isoweek` on the x-axis
-   Weeks with zero cases must be displayed

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/1532091/48142218-a678ff80-e2ac-11e8-8832-f5b1babe904a.png)

There is fake json data available at `cbs/Source/Analytics/Web.React/src/assets/data/epicurve_by_week.json`.

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This fake json data file has 4 'levels':

- all (i.e. all the data -- national level)
- district
- region
- village

The 'geographical value' is stored in 'geo'. i.e. if `level=district`, then maybe `geo=Western Norway`. If `level=village` then maybe `geo=Oslo`.

`Sex` is:

- All
- Male
- Female

`Age` is:

- All
- Age <5
- Age 5+

`pop` contains the population if it exists. Otherwise it is -9.

**Comment by karolikl** [comment]
/api/Analysis/{from}/{to}/{timeAggregation} solved this. The only thing missing is the support for geo, which has been documented in a separate issue (#990)
