### ISSUE TITLE
Epicurve by day frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#848]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/849.

Here we display a daily `epicurve`.

![unnamed-chunk-2-1](https://user-images.githubusercontent.com/1532091/48143144-77fc2400-e2ae-11e8-8b4c-34b53140a6f2.png)

Important to note:

-   Unclear the best way to display date on the x-axis
-   Days with zero cases must be displayed

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-day.json`

This fake json data file has 4 'levels':

- all (i.e. all the data -- national level)
- district
- region
- village

The 'geographical value' is stored in 'geo'. i.e. if `level=district`, then maybe `geo=Western Norway`. If `level=village` then maybe `geo=Oslo`.

`Sex` is:

- All
- Male
- Female

`Age` is:

- All
- Age <5
- Age 5+

`pop` contains the population if it exists. Otherwise it is -9.

**Comment by raubreywhite** [comment]
Please note that in principle, this will be superseded by: https://github.com/IFRCGo/cbs/issues/922

**Comment by karolikl** [comment]
A static version of this chart has been generated in the Web Template using Highcharts, see `Documentation/Projects/Analytics/Web%20Mockup/Epicurvebyday.html`

The Highchart has also been moved to the React frontend, see `/Source/Analytics/Web/src/components/Epicurvebyday.js`
But this is still created using static data (in the .js file). 

**Remaining work:**
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by karolikl** [comment]
Querying backend for data is now complete. 

**Remaining work:**
- Generate chart based on user input, as mentioned by Richard above (#922)

**Comment by raubreywhite** [comment]
Done!
