### ISSUE TITLE
Epicurve by day backend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#849]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the backend for https://github.com/IFRCGo/cbs/issues/848.

Here we display a daily `epicurve`.

![unnamed-chunk-2-1](https://user-images.githubusercontent.com/1532091/48143144-77fc2400-e2ae-11e8-8b4c-34b53140a6f2.png)

Important to note:

-   Unclear the best way to display date on the x-axis
-   Days with zero cases must be displayed

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-day.json`

This fake json data file has 4 'levels':

- all (i.e. all the data -- national level)
- district
- region
- village

The 'geographical value' is stored in 'geo'. i.e. if `level=district`, then maybe `geo=Western Norway`. If `level=village` then maybe `geo=Oslo`.

`Sex` is:

- All
- Male
- Female

`Age` is:

- All
- Age <5
- Age 5+

`pop` contains the population if it exists. Otherwise it is -9.

**Comment by karolikl** [comment]
This is compete, but the geo filtering has been moved to a separate issue (#990)
