### ISSUE TITLE
Epicurve by week dodged by age frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#850]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/851.

![unnamed-chunk-3-1](https://user-images.githubusercontent.com/1532091/48143518-3cae2500-e2af-11e8-9952-7c34cb4ab834.png)

Here we display a weekly `epicurve` with two columns for each week,
showing the ages side-by-side.

Important to note:

-   We display `year-isoweek` on the x-axis
-   Weeks with zero cases must be displayed

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by raubreywhite** [comment]
Please note that in principle, this will be superseded by: https://github.com/IFRCGo/cbs/issues/922

**Comment by karolikl** [comment]
A static version of this chart has been generated in the Web Template using Highcharts, see `Documentation/Projects/Analytics/Web%20Mockup/Epicurvebyweekdodgedbyage.html`

The Highchart has also been moved to the React frontend, see `/Source/Analytics/Web/src/components/Epicurvebyweekdodgedbyage.js`
But this is still created using static data (in the .js file). 

**Remaining work:**
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by raubreywhite** [comment]
No longer relevant with new UI plan.
