### ISSUE TITLE
Epicurve by week dodged by age backend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#851]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the backend for https://github.com/IFRCGo/cbs/issues/850.

![unnamed-chunk-3-1](https://user-images.githubusercontent.com/1532091/48143518-3cae2500-e2af-11e8-9952-7c34cb4ab834.png)

Here we display a weekly `epicurve` with two columns for each week,
showing the ages side-by-side.

Important to note:

-   We display `year-isoweek` on the x-axis
-   Weeks with zero cases must be displayed

**Comment by raubreywhite** [comment]
I THINK THIS IS ALREADY COVERED BY https://github.com/IFRCGo/cbs/issues/846 AS THE DATA SHOULD BE THE SAME

Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by karolikl** [comment]
Finished.
