### ISSUE TITLE
Epicurve by day dodged by age frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#852]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/853.

![unnamed-chunk-4-1](https://user-images.githubusercontent.com/1532091/48143970-3cfaf000-e2b0-11e8-947c-4627205428fa.png)

Here we display a daily `epicurve` with two columns for each day,
showing the ages side-by-side.

Important to note:

-   Unclear the best way to display date on the x-axis
-   Days with zero cases must be displayed

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-day.json`

This is an extension of the graph Epicurve by day" (frontend issue: https://github.com/IFRCGo/cbs/issues/848, backend issue: https://github.com/IFRCGo/cbs/issues/849).

**Comment by raubreywhite** [comment]
Please note that in principle, this will be superseded by: https://github.com/IFRCGo/cbs/issues/922

**Comment by karolikl** [comment]
**Remaining work:**
- Generate a static version of this chart in the Web Template using Highcharts: `Documentation/Projects/Analytics/Web%20Mockup/Epicurvebydaydodgedbyage.html`
- Add Highchart to the React frontend
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by raubreywhite** [comment]
No longer relevant with new UI plan.
