### ISSUE TITLE
Age and sex distribution over different time frames frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#854]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/855.

![unnamed-chunk-5-1](https://user-images.githubusercontent.com/1532091/48144124-93682e80-e2b0-11e8-85a3-7fe0fe0b1202.png)

-   We display the number of cases, split by age/sex on the x-axis
-   We need the ability to display different time frames (e.g. per week,
    last week, over multiple weeks)

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by karolikl** [comment]
A static version of this chart has been generated in the Web Template using Highcharts, see `Documentation/Projects/Analytics/Web%20Mockup/Ageandsexdistributionoverdifferenttimeframes.html`

**Remaining work:**
- Add Highchart to the React frontend
- Query backend for data using the AgeAndSexDistributionAggregationByDateRange query found in `Source/Analytics\Web\Features\AgeAndSexDistribution\AgeAndSexDistributionAggregationByDateRange.js`
- Generate chart based on user input, as mentioned by Richard above (#922)

**Comment by karolikl** [comment]
The Highchart has been added to the React frontend.

**Remaining work:**
- Query backend for data using the AgeAndSexDistributionAggregationByDateRange query found in `Source/Analytics\Web\Features\AgeAndSexDistribution\AgeAndSexDistributionAggregationByDateRange.js`
- Generate chart based on user input, as mentioned by Richard above (#922)

**Comment by raubreywhite** [comment]
These are now simple data values displayed in text. Relevant for Pages 1 and 2.

https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md

**Comment by raubreywhite** [comment]
Finished in Senegal.
