### ISSUE TITLE
Weekly epicurve graph showing cases per geographical area (frontend)

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#858]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/859.

The graph should be possible to use for region, district and village.
- If it is for a region each column should show details per district
- If it is for a district each columns should show details per village
- We display `year-isoweek` on the x-axis
- Weeks with zero cases must be displayed
- Y-axis remains the same height for all panels, to allow for easy comparison (should this be a toggle?)

The following example is for "Region 1" who has 3 districts.
![image](https://user-images.githubusercontent.com/1155078/58708480-3a7cf680-83b8-11e9-8ed0-4a77efb74e19.png)

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by raubreywhite** [comment]
Please note that in principle, this will be superseded by: https://github.com/IFRCGo/cbs/issues/922

**Comment by karolikl** [comment]
**Remaining work:**
- Generate a static version of this chart in the Web Template using Highcharts: `Documentation/Projects/Analytics/Web%20Mockup/Weeklyepicurvesbygeographicalarea.html`
- Add Highchart to the React frontend
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by raubreywhite** [comment]
This now falls under "Page 3" https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md

**Comment by cathinkaw** [comment]
For overall reference of how the graph is thought to be used on a page:
![image](https://user-images.githubusercontent.com/1155078/58708883-330a1d00-83b9-11e9-8498-dd53399fed15.png)

**Comment by cathinkaw** [comment]
Some good comments from @raubreywhite on Slack regarding this task. There may be an issue with too many districts/villages and showing them all with colours/patterns. Maybe the biggest 7 should be shown and the rest as "others". http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3
