### ISSUE TITLE
Weekly epicurves by geographical area backend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#859]
This is the backend for https://github.com/IFRCGo/cbs/issues/858.

The backend should be able to provice data as follows:
-   We should be able to choose the granularity of geographical
    area (region/district/village)
-   We display `year-isoweek` on the x-axis
-   Weeks with zero cases must be displayed
-   Y-axis remains the same height for all panels, to allow for easy
    comparison (this should probably be a toggle?)

**Comment by raubreywhite** [comment]
I THINK THIS IS ALREADY COVERED BY https://github.com/IFRCGo/cbs/issues/846 AS THE DATA SHOULD BE THE SAME

Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by raubreywhite** [comment]
This now falls under our "Page 3" https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md

**Comment by cathinkaw** [comment]
I will define the actualt input/expected output better later
