### ISSUE TITLE
Map by geographical area frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#860]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/861.

![unnamed-chunk-8-1](https://user-images.githubusercontent.com/1532091/48145316-e4792200-e2b2-11e8-9553-6b7c08e7ae85.png)

Here we display a map with categorized number of cases.

Important to note:

-   We should probably be able to choose the granularity of geographical
    area (region/district/village)
-   We should be able to change the time-frame
-   Not reporting regions should be highlighted
-   The graphing/outcome should be categorical NOT a continuous
    gradient. Probably no more than 4 categories.
-   Very important: We should also implement one version where the
    outcome is:
    `(number of reported cases)/(estimation population)*10000` (i.e.
    number of reported cases per 10.000 population).

**Comment by karolikl** [comment]
A static version of this chart has been generated in the Web Template using Highcharts, see `Documentation/Projects/Analytics/Web%20Mockup/Mapbygeographicalarea.html`

**Remaining work:**
- Add Highchart to the React frontend
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data
