### ISSUE TITLE
District/Person reporting funnel plot B frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#871]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/872

![unnamed-chunk-11-1](https://user-images.githubusercontent.com/1532091/48157321-945c8880-e2cf-11e8-80a8-85b2e85f0d6c.png)

The idea of this funnel plot is to identify districts/people who are reporting worse than expected.

For each month, we count the number of messages sent, and the number of correctly sent messages. From this, we generate an "expected proportion of received messages that are correct" (e.g. 80%). Then, for each district/person, we calculate the 2.5th and 97.5th percentiles according to the binomial distribution. That is, (e.g. if Oslo sent 40 messages) what is the 2.5th and 97.5th percentile of a Binom(n=40, p=0.8) distribution. These percentiles are our boundaries as displayed in the graph.

Important to note:

-   We should be able to switch between district/people/other grouping measure
-   We should be able to change the time-frame
-   Maybe only the people/groups who are "lower than expected" should be highlighted in some way?

**Comment by karolikl** [comment]
**Remaining work:**
- Generate a static version of this chart in the Web Template using Highcharts: `Documentation/Projects/Analytics/Web%20Mockup/DistrictPersonreportingfunnelplotB.html`
- Add Highchart to the React frontend
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by raubreywhite** [comment]
No longer relevant with new UI plan.
