### ISSUE TITLE
Allow non-authenticated users on the dev-cluster

### ISSUE THREAD

**Issue by jakhog** [IFRCGo/cbs#874]
We need to get easier access for developers to the dev-cluster, so that they can look at what's going on. Since there should be just random data there, we shouldn't really need any authentication at all.

**Comment by einari** [comment]
The easiest thing that could possibly work is to build it either in Development mode - or add another flag that will skip this. Look here: https://github.com/IFRCGo/cbs/blob/master/Source/Navigation/authentication.service.ts - line 62.

**Comment by jakhog** [comment]
Now it's built and deployed in dev-mode
