### ISSUE TITLE
As a data owner, I want to be able to register an alert rule - Frontend

### ISSUE THREAD

**Issue by mfredbo** [IFRCGo/cbs#906]
**Describe the solution you'd like**
The solution should look like the sketch attached here.

Let us know if you need any changes. Ask @mfredbo or @gryha 

**What needs to be done frontend**:
*General for all input fields*: The input for the numbers should also be shown as red numbers above the field, including the unit used for that field (for example km, hours, case).
*Health risk name*: This will be a drop down menu.
*Cases (in number)*: This is the number of cases which will trigger an alert. This will be a number.
*I want to count the cases...* :  When you click on "Other" this should open up more below. There will be a new sketch including this view. Ask @gryha .
*Distance between cases*:  Number.

**Comment by gryha** [comment]
<img width="610" alt="alert rule dec 18 2019" src="https://user-images.githubusercontent.com/20842471/51392172-854a5000-1b34-11e9-8e91-6815798334d6.png">
