### ISSUE TITLE
MVP Backend - An alert rule is triggered based on one case registered

### ISSUE THREAD

**Issue by mfredbo** [IFRCGo/cbs#920]
**MVP - Alert rule is triggered**
Once one _case is registered_ (on one health risk), I want an alarm to be triggered. This is backend.

This is the MVP. 

I.e., later on, the alarm will later on be triggered based on also threshold (such as number of cases, number of hours between the cases registered, and distance between cases registered).

Please define this task more detailed if needed, or ask me if you have any questions.

**Comment by Velcrow81** [comment]
We improved it to be threshold and time dependant. Distance is ignored for now
