### ISSUE TITLE
User input in frontend to generate Epicurve charts

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#922]
The Epicurve charts will be displayed under a single submenu item in Analytics called "Epicurve". 

The user must be able to specify the following input to generate the chart.

Filters/selectors (i.e. refining the data):
- From date
- To date
- Type of chart: "By week" or "By day"
- Sex: (Male, Female) - note "All" is generated by selecting both 'M' and 'F'
- Age: (<5, >=5)- note "All" is generated by selecting both '<5' and '>=5'
- Geographical region
- Health risk

How would you like to present the data:
- facet_grid: (age, sex, geographical region, health risk)
- facet_wrap: (age, sex, geographical region, health risk)
- dodge: (age, sex, geographical region, health risk)

Note: these terms (`facet_grid`, `facet_wrap`, `dodge`) are defined in index.md.

Based on these input, the charts in https://github.com/IFRCGo/cbs/issues/858, https://github.com/IFRCGo/cbs/issues/856, https://github.com/IFRCGo/cbs/issues/852, https://github.com/IFRCGo/cbs/issues/850, https://github.com/IFRCGo/cbs/issues/848, and https://github.com/IFRCGo/cbs/issues/845 should be generated.

**Comment by raubreywhite** [comment]
No longer relevant with new UI plan.
