### ISSUE TITLE
MVP Frontend + UI: Make a page where all the alert rules are listed

### ISSUE THREAD

**Issue by mfredbo** [IFRCGo/cbs#923]
**Description**
This page should include a list off all registered alert rules. It should also be possible to open an alert rule and look at it.

Editing and deleting alert rules will be a feature implemented later on.

**Comment by gryha** [comment]
Here's the link to user interface in UXpin: https://preview.uxpin.com/cdf72b60c80d94cf32507cadfaa0b1888f3d66f2#/pages/101874840
