### ISSUE TITLE
Navigation / Menu

### ISSUE THREAD

**Issue by einari** [IFRCGo/cbs#93]

**Comment by alexanderhoset** [comment]
Idea on how to fix this is added to the design mockup that is now merged to the master 

- Main nav created to expose the bounded contexts 
- The standalone bounded contexts will expose the pages they want in their own context

As a result we have a design that is context independent, and the contexts can update  without checking with CORE

**Comment by alexanderhoset** [comment]
#373 is the solution for this, do we close this task @einari ?

**Comment by einari** [comment]
Agree. Duplicate - closing this.
