### ISSUE TITLE
Add Email settings in kubernetes environments

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#958]
"ALERT_MAILER_FROM"
"ALERT_MAILER_HOST"
"ALERT_MAILER_USER");
"ALERT_MAILER_PASSWORD");

int port = 25;
"ALERT_MAILER_PORT"
bool useSsl = false;
"ALERT_MAILER_USESSL"

These settings can be changed if they turn out to not make sense for I.E. send grid

Also, email sending directly from alerts is only for MVP. Once Notification gateway can handle it, that should be used in stead

**Comment by Velcrow81** [comment]
I suggest @eprom look into this. Agree?

**Comment by eprom** [comment]
> I suggest @eprom look into this. Agree?

@Velcrow81 Yes, I am looking into it 👍

**Comment by eprom** [comment]
@Velcrow81 
1. I created a secret under "cbs-app" namespace in the dev cluster with all needed sendgrid variables.
2. Updated the Reporting-core pod deployment to consume the secret

Seems everything is in place.

**Comment by Velcrow81** [comment]
Do we need to do any changes to get at these secrets @eprom ?

**Comment by gardnk** [comment]
Closing as moved to done
