### ISSUE TITLE
Question: What happened to the TestDataGeneator?

### ISSUE THREAD

**Issue by eloekset** [IFRCGo/cbs#966]
In step 4 of https://github.com/IFRCGo/cbs/wiki/How-to-contribute, a TestDataGenerator is mentioned to seed the database.

I've searched for PRs about TestDataGenerator and found it was added to the UserManagement/Web folder. I'm able to trace its history up to commit b4eb8f33, but I'm not able to find it in my working folder. I'm not able to invoke it like documented in the wiki.

Is the wiki outdated, or am I missing something?

**Comment by karolikl** [comment]
The way we generate testdata was changed during the previous codeathon, and it looks like the "How to contribute" guide hasn't been updated so thanks for pointing that out! I'll make sure it's updated. 

The way test data is generated now is by using a Command, as explained here for the Analytics bounded context (where we first issue a command to copy test data from a json file to MongoDB, and then a query to query against it): https://github.com/IFRCGo/cbs/tree/master/Source/Analytics#populating-the-database-with-test-data 

If you want to see how it's implemented, you can have a look here: 
https://github.com/IFRCGo/cbs/tree/master/Source/Analytics/Domain/CaseReports/TestData

**Comment by karolikl** [comment]
The documentation on how to populate the database with test data has been updated.
