### ISSUE TITLE
Rename from case to report

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#974]
The reason for moving away from case is that is often related to a sick human, but fire, flooding and animal die off is usually not considered a case. A report can cover both

**Comment by woksin** [comment]
This really seems like something that should be done in every bounded context that deals with case report

**Comment by smithmx** [comment]
I would consider this carefully before making the change.  I've heard the domain experts talk a lot about cases.  This means that Case is part of the Ubiquitous Language and should be modelled.  You can always minimize the duplication of code if the implementations are identical by the judicious use of inheritance for example, or a flag to indicate which it is.  If the difference between a Case and a Report is not something you want to burden the Data Collectors with, you can deduce what it is from the values.

**Comment by Velcrow81** [comment]
Thanks for your input. I have heard they use it to, but they are trying to move away from it. I will wait before I submit my pull request, to see if this stablizes at a specific term.

**Comment by smithmx** [comment]
That changes everything.  Check and see.  It might be that they want the CBS app to help drive the change in terminology.  If so, then Sindre is right and this should be across Bounded Contexts.

**Comment by Velcrow81** [comment]
@aninek : Any thoughts on this. Changing from case to report should be reflected in all BC. Maybe CaseReport should be AggregateReport and Case should be Report

**Comment by Velcrow81** [comment]
My recommendation is to leave it as it is. The work required to change this and make it the same all over is larger than I think it is worth. I vote to keep case in Alerts, so it makes sense with naming in Reporting

**Comment by Velcrow81** [comment]
Is it difficult to change names on events when there are existing events in prod? Is it tied to a guid or the event name in the event store?

**Comment by aninek** [comment]
Hmmm... There seems to be agreement among domain experts that "report" is more accurate than case. Of course, we talk about cases (and will continue to do so), but what the volunteers send is actually a report (of a case, event or other)  In surveillance, this can also be called a signal, or an alert, report, message, etc - there is no universal or ubiquitous terminology as we are lacking global standards. We are working on this in parallell, which means we are also learning as we go.. I think Case might be short for case report, but we should really drop the "case" from the terminology as the reports wont necessarily be about cases (of suspected disease). @eprom this is perhaps not a priority to change in the code, but we can add it to our dictionary?

**Comment by woksin** [comment]
@einari should answer that, @Velcrow81

**Comment by Velcrow81** [comment]
I look forward to input from @einari. If it is a lot of pain involved in changing the name (and possibly the id since it is called CaseReportId and CaseId), we should discuss more during a sync meeting or code evening on if we should do this and how we go about doing this. If events are not identified by a GUID, maybe they should be in the future (to allow some changes since it is usually at the end of a project that you start to understand the domain)

**Comment by einari** [comment]
Event types are identified by GUID - ArtifactId. So that should just work. As for the readmodels, the consequence there is that the collection-name in Mongo needs to change. I think we should, we have an opportunity to do it when we will deploy a new version into production. We need to do quite a bit of other things at that point anyways - amongst others move from Cosmos to our in-cluster Mongo solution.

**Comment by einari** [comment]
I've started a list of things for us to keep track of things we need to do when deploying a new version
 - #976

**Comment by Velcrow81** [comment]
What about the Id properties? They are called CaseId and CaseReportId. Is it easy to change these to i.e. Id? And about the read models, can't we just give the event processors new GUIDs and then they should automatically recreate new read models?

**Comment by einari** [comment]
Your approach is much better. Replay - obviously. So when we migrate EventStore, we set all event processors to zero and first startup it will play all the events against them and voila it will have created the read models again. 

This is an interesting exercise. But, if there for some reason is a problem with that, it would mean that we broke something and would need to figure out what that is then.

**Comment by Velcrow81** [comment]
Cool. And regarding the change on Id naming?

**Comment by einari** [comment]
That would be fine as well. It will then be a completely new read model - for the new database we will be setting up for the new version when we publish that. So its basically a clean slate with only the events coming over - which are artifact Id based.

**Comment by woksin** [comment]
As far as I understand it you don't even need to change the event processors in the code before it goes to prod, because they have, in fact, never been processed :)

**Comment by Velcrow81** [comment]
@woksin : This could be done for i.e. CaseReportRecieved event since that is in production (if we rename from case there too). I just sent a pull request were we renamed from Case to Report. Guess that might be the same name for CaseReport to, but it will mean differnt things in each bounded context. A report in Alert will never contain aggragate information, but it can that in Reporting. Does that make sense?
