### ISSUE TITLE
Composition - how to - research / decide

### ISSUE THREAD

**Issue by einari** [IFRCGo/cbs#98]
IFRAME or not - or what..

**Comment by alexanderhoset** [comment]
The current design has a fix for this by having the main new a part of Portal . Then all the projects have their own sub navigation. 

Then again, the 3-4 frontends, need to be revisited if needed to split up like today ....

Hope we can use some minutes on this during the code night event,   @einari , @anderaus , @karolikl

**Comment by alexanderhoset** [comment]
#373  is the solution for this, do we close this task @einari ?

**Comment by einari** [comment]
Thats correct - I close this - duplicate
