### ISSUE TITLE
Retrieve data collector KPIs from backend

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#992]
Currently, the number of data collectors in Analytics is static:
![image](https://user-images.githubusercontent.com/5235776/55498055-f3d28080-5642-11e9-91b5-f6e32188482f.png)

The total number of data collectors and the number of active data collectors needs to be retrieved from the backend: 
GET /api/KPI/{from}/{to}

**Format of response:** 
`{
  "caseReports": {
    "totalNumberOfReports": 2056,
    "reportedHealthRisks": [
      {
        "name": "Cholera",
        "numberOfReports": 736
      },
      {
        "name": "Acute Watery Diarrhea",
        "numberOfReports": 680
      },
      {
        "name": "Measels",
        "numberOfReports": 640
      }
    ]
  },
  "dataCollectors": {
    "totalNumberOfDataCollectors": 24,
    "activeDataCollectors": 9,
    "inactiveDataCollectors": 15
  },
  "alerts": {
    "totalNumberOfAlerts": 3
  }
}`

**Comment by gardnk** [comment]
This is done in the new analytics
